import { useEffect, useRef, useState } from 'react';
import { useReadiness } from '../hooks/useReadiness';
import { mapSensors } from '../simulation/sensorMapping';
import { EXPERIMENTS, DEFAULT_EXPERIMENT } from './experiments';
import type { ExperimentConfig, ExperimentId, FlyMode } from './experiments';
import { flyResult, flySummary } from './simulation';
import type { FlyResult } from './simulation';
import { useFlySimulation } from './useFlySimulation';
import { FlyEmbodiment } from './FlyEmbodiment';
import type { PaintStats } from './FlyCanvas';
import { compareTrial } from './trials';
import { StimulationLab } from './StimulationLab';
import AnatomicalViewer from './AnatomicalViewer';
import './fly-lab.css';
const fixed=(n:number|null|undefined,d=2)=>n==null?'—':n.toFixed(d);
export default function VirtualFlyLab(){
  const {sim,epoch,toggle,reset,step,stepping}=useFlySimulation(),readiness=useReadiness();
  const [config,setConfig]=useState<ExperimentConfig>({...DEFAULT_EXPERIMENT}),[showPath,setShowPath]=useState(true),[inspector,setInspector]=useState(true);
  const [results,setResults]=useState<FlyResult[]>([]),[comparing,setComparing]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState('');
  const [showAnatomy,setShowAnatomy]=useState(true);
  const [paint,setPaint]=useState<PaintStats|null>(null),[logBytes,setLogBytes]=useState(0);
  const request=useRef<AbortController|null>(null),current=useRef(sim);current.current=sim;
  useEffect(()=>()=>request.current?.abort(),[]);
  useEffect(()=>{const timer=setInterval(()=>setLogBytes(new TextEncoder().encode(JSON.stringify({path:current.current.path,telemetry:current.current.telemetry})).byteLength),1000);return()=>clearInterval(timer);},[]);
  const configure=(next:ExperimentConfig)=>{request.current?.abort();request.current=null;setComparing(false);setProgress('');setError('');setResults([]);setConfig(next);reset(next);};
  const compare=async()=>{const abort=new AbortController();request.current=abort;setComparing(true);setError('');setResults([]);
    try{const runs=await compareTrial(config,abort.signal,undefined,setProgress);if(request.current===abort&&!abort.signal.aborted)setResults(runs);}
    catch(e){if(request.current===abort)setError(String(e));}
    finally{if(request.current===abort){request.current=null;setComparing(false);setProgress('');}}};
  const summary=flySummary(sim),response=sim.neural.response;
  const input=response&&sim.config.mode==='malecns'?response.stimulus:mapSensors(sim.fly.sensors);
  const controlLabel=sim.config.mode==='malecns'?'MaleCNS-derived':'Rule-Based';
  const exportLogs=()=>{const blob=new Blob([JSON.stringify({note:'Virtual Fly Lab engineering simulation; all times simulated seconds unless labeled latency.',current:flyResult(sim),comparisons:results},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`virtual-fly-${config.experiment}-${config.seed}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <main className="fly-lab">
    <div className="fly-title"><div><p className="fly-kicker">BIOBUG / RESEARCH EXPERIENCE 02</p><h1>Virtual Fly Lab<span>.</span></h1><p>Experimental connectome-driven simulation</p></div><div className="fly-readiness" role="status">{readiness.state==='ready'?'MALECNS READY':readiness.state==='loading'?'LOADING MALECNS…':'MALECNS UNAVAILABLE / STARTING'}<small>Rule-Based remains available offline</small></div></div>
    <p className="fly-premise">One virtual body. Real structural connectivity. An observable feedback loop.</p>
    <section className="fly-config fly-card" aria-label="Experiment configuration">
      <label>EXPERIMENT<select disabled={sim.running||comparing} value={config.experiment} onChange={e=>configure({...config,experiment:e.target.value as ExperimentId})}>{EXPERIMENTS.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>
      <label>SEED<input type="number" min={0} max={4294967295} step={1} value={config.seed} disabled={sim.running||comparing} onChange={e=>{const seed=Number(e.target.value);if(Number.isInteger(seed)&&seed>=0&&seed<=4294967295)configure({...config,seed});}}/></label>
      <label>DURATION<select value={config.duration} disabled={sim.running||comparing} onChange={e=>configure({...config,duration:Number(e.target.value)})}>{[30,60,120].map(n=><option key={n} value={n}>{n} simulated seconds</option>)}</select></label>
      <div className="fly-mode" role="group" aria-label="Fly controller">{(['rule-based','malecns'] as FlyMode[]).map(mode=><button key={mode} aria-pressed={config.mode===mode} disabled={sim.running||comparing||(mode==='malecns'&&readiness.state!=='ready')} onClick={()=>configure({...config,mode})}>{mode==='rule-based'?'RULE-BASED':'MALECNS-DERIVED'}</button>)}</div>
      <label><input type="checkbox" checked={showAnatomy} onChange={e=>setShowAnatomy(e.target.checked)}/>ANATOMICAL VIEWER</label>
      <small>Configuration changes start a fresh experiment. Each controller gets the same start pose, geometry, seed and duration.</small>
    </section>
    <div className="fly-workspace"><section className="fly-arena fly-card"><div className="fly-arena-heading"><div><p className="fly-kicker">{controlLabel} / SEED {config.seed}</p><h2>{EXPERIMENTS.find(e=>e.id===config.experiment)!.name}</h2></div><span className="fly-run-status">{sim.completed?'EXPERIMENT COMPLETE':sim.neural.status==='offline'?'BACKEND OFFLINE':sim.neural.status==='waiting'?'NEURAL WAIT · BODY HELD':sim.running?'RUNNING':'PAUSED'}</span></div>
      <FlyEmbodiment sim={sim} showPath={showPath} comparisons={results} onSelect={()=>setInspector(true)} onPerformance={setPaint}/>
      <div className="fly-controls"><button className="fly-primary" disabled={comparing||sim.completed||(!sim.running&&config.mode==='malecns'&&readiness.state!=='ready')} onClick={toggle}>{sim.running?'PAUSE EXPERIMENT':sim.elapsed?'RESUME':'START EXPERIMENT'}</button><button onClick={()=>configure(config)}>RESET EXPERIMENT</button><button disabled={sim.running||stepping||comparing||sim.completed||config.mode!=='malecns'||readiness.state!=='ready'} onClick={()=>void step()}>STEP NEURAL UPDATE</button><label><input type="checkbox" checked={showPath} onChange={e=>setShowPath(e.target.checked)}/>SHOW PATH</label><span>{sim.elapsed.toFixed(1)} / {config.duration} s</span></div>
      <div className="fly-map-legend"><span>Mint: current path</span><span>Amber: compared Rule-Based</span><span>Violet dashed: compared MaleCNS</span><span>Shading: visited 30-unit cells</span></div>
      <p className="fly-small">Body styles and instrumentation are illustrative. Animation reads the existing pose; it does not simulate flight or full leg biomechanics. Rays are engineering proximity channels, not reconstructed sensory organs.</p>
    </section>{showAnatomy?<AnatomicalViewer key={epoch} sim={sim}/>:(<section className="fly-neural fly-card" aria-label="Live neural activity"><p className="fly-kicker">CLOSED LOOP / LIVE VALUES</p><h2>From geometry to movement</h2>
      <div className="fly-signal"><span className="fly-evidence engineering">ENGINEERING MODEL</span><h3>Simulated tactile input</h3>{(['left','front','right'] as const).map(side=><label key={side}><span>{side.toUpperCase()}</span><meter min={0} max={1} value={input[side]}/><b>{input[side].toFixed(3)}</b></label>)}<small>{response&&config.mode==='malecns'?`Last neural sample at ${fixed(sim.neural.sampleTime)} s`:'Current geometry-derived values'}</small></div>
      <div className="fly-arrow">↓ Engineering sensory mapping</div><div className="fly-signal"><span className="fly-evidence real">REAL DATA</span><h3>ProLN → intermediates → DNa02</h3><p>{response?`${response.graph.neurons} neurons · ${response.graph.edges} edges · ${response.graph.structural_contacts.toLocaleString()} contacts`:'Awaiting actual neural response'}</p><small>{response?`${response.input_active} inputs active · MaleCNS ${response.version}`:'Reuses the existing two-hop controller graph'}</small></div>
      <div className="fly-arrow">↓ Simulated dynamics · 20 steps from rest</div><div className="fly-readouts"><div><span>DNa02-L</span><strong>{fixed(response?.dna02.L.peak,4)}</strong><small>{response?`Real ID ${response.dna02.L.id}`:'No measurement'}</small></div><div><span>DNa02-R</span><strong>{fixed(response?.dna02.R.peak,4)}</strong><small>{response?`Real ID ${response.dna02.R.id}`:'No measurement'}</small></div></div>
      <span className="fly-evidence engineering">ENGINEERING MODEL / ACTIVITY</span><div className="fly-arrow">↓ Engineering motor decoder</div><div className="fly-motor"><strong>{sim.fly.turning.replaceAll('_',' ')}</strong><p>{config.mode==='rule-based'?'Conventional navigation baseline. Neural values are not generated.':!sim.running?'Body paused. Resume to apply a fresh neural decision.':sim.neural.status==='waiting'?'Movement held until a valid response arrives.':sim.neural.decision?.reason??'Awaiting the first neural decision.'}</p></div><div className="fly-arrow">↺ Movement → new sensory input</div>
      {sim.neural.error&&<p role="alert" className="fly-error">{sim.neural.error} No fallback is applied silently. Retry or choose Rule-Based while paused.</p>}
    </section>)}</div>
    <section className="fly-metrics" aria-label="Fly experiment metrics">{[['DISTANCE',`${fixed(summary.distance)} u`],['TURN BOUTS',summary.turns],['BLOCKED STEPS',summary.blocked],['COLLISION ATTEMPTS',summary.collisionAttempts],['TIME MOVING',`${fixed(summary.movingTime)} s`],['VISITED AREA',`${fixed(summary.coverage)}%`]].map(([name,value])=><div key={name}><span>{name}</span><strong>{value}</strong></div>)}</section>
    <div className="fly-columns"><section className="fly-card"><p className="fly-kicker">SIMULATED ACTIVITY / OBSERVED RESPONSE PEAKS</p><h2>DNa02 across decisions</h2><NeuralTrace rows={sim.telemetry}/><p>Each point is a peak from an independent 20-step neural evaluation, not measured physiology or continuous activity between requests.</p><dl><div><dt>Peak L / R</dt><dd>{fixed(summary.peakDNa02L,4)} / {fixed(summary.peakDNa02R,4)}</dd></div><div><dt>Mean |L − R|</dt><dd>{fixed(summary.meanAsymmetry,4)}</dd></div><div><dt>Engineering frontal fallbacks</dt><dd>{summary.fallbacks}</dd></div></dl><h3>Top reported intermediate types</h3><p>{response?.top_intermediate_types.map(n=>`${n.type}: ${n.cumulative_activity.toFixed(3)}`).join(' · ')||(response?'No intermediates active in the last sample':'No neural measurement yet')}</p></section>
    <section className="fly-card"><button className="fly-inspector-toggle" aria-expanded={inspector} onClick={()=>setInspector(!inspector)}>VIRTUAL FLY INSPECTOR {inspector?'−':'+'}</button>{inspector&&<><dl><div><dt>Body position</dt><dd>{fixed(sim.fly.position.x)}, {fixed(sim.fly.position.y)}</dd></div><div><dt>Heading / actual speed</dt><dd>{fixed(sim.fly.heading*180/Math.PI)}° / {fixed(sim.fly.velocity)} u/s</dd></div><div><dt>Controller</dt><dd>{controlLabel}</dd></div><div><dt>Environment / seed</dt><dd>{config.experiment} / {config.seed}</dd></div><div><dt>Elapsed time</dt><dd>{fixed(sim.elapsed)} s</dd></div><div><dt>Tactile L / F / R</dt><dd>{[input.left,input.front,input.right].map(n=>n.toFixed(3)).join(' / ')}</dd></div><div><dt>Active inputs / DNa02 L / R</dt><dd>{response?.input_active??'—'} / {fixed(response?.dna02.L.peak,4)} / {fixed(response?.dna02.R.peak,4)}</dd></div><div><dt>Motor state</dt><dd>{sim.fly.turning.replaceAll('_',' ')}</dd></div>{(['left','front','right'] as const).map(side=><div key={side}><dt>{side} ray distance</dt><dd>{fixed(sim.fly.sensors[`${side}Distance`])} u</dd></div>)}</dl><p>Neural state is local to this experiment. Velocity is body state, not an added biological proprioceptive pathway.</p></>}
      <h3>Measured runtime</h3><dl><div><dt>Neural HTTP mean / p95</dt><dd>{fixed(summary.meanLatencyMs)} / {fixed(summary.p95LatencyMs)} ms</dd></div><div><dt>Neural responses</dt><dd>{summary.neuralSamples}</dd></div><div><dt>2D canvas paints / second</dt><dd>{fixed(paint?.fps,1)}</dd></div><div><dt>Physics steps / wall second</dt><dd>{fixed(paint?.physicsStepsPerSecond,1)}</dd></div><div><dt>Mean canvas paint</dt><dd>{fixed(paint?.paintMs,2)} ms</dd></div><div><dt>Serialized path + telemetry</dt><dd>{(logBytes/1024).toFixed(1)} KiB</dd></div></dl><p>2D canvas measurements apply while the simple body or arena map is visible. Render updates target ~30 Hz. Serialized log size is not total browser heap. No connectome matrix is downloaded to this lab.</p>
    </section></div>
    <section className="fly-card fly-comparison"><p className="fly-kicker">PAIRED EXPERIMENT / IDENTICAL INITIAL CONDITIONS</p><h2>Compare measured behavior</h2><p>Runs fresh Rule-Based and MaleCNS-derived trials for the selected arena, seed and duration. Current body stays paused; comparison paths overlay the arena.</p><div className="fly-controls"><button disabled={sim.running||comparing||readiness.state!=='ready'} onClick={()=>void compare()}>RUN BOTH CONTROLLERS</button>{comparing&&<button onClick={()=>request.current?.abort()}>CANCEL COMPARISON</button>}<button disabled={comparing} onClick={exportLogs}>EXPORT EXPERIMENT JSON</button><span role="status">{progress}</span></div>{error&&<p role="alert" className="fly-error">{error}</p>}
      {results.length===2?<div className="fly-table-scroll"><table><thead><tr><th>Controller</th><th>Distance</th><th>Turns</th><th>Blocked / collisions</th><th>Time moving</th><th>Visited area</th><th>HTTP mean / p95</th></tr></thead><tbody>{results.map(r=><tr key={r.summary.config.mode}><th>{r.summary.config.mode==='rule-based'?'Rule-Based':'MaleCNS-derived'}</th><td>{fixed(r.summary.distance)} u</td><td>{r.summary.turns}</td><td>{r.summary.blocked} / {r.summary.collisionAttempts}</td><td>{fixed(r.summary.movingTime)} s</td><td>{fixed(r.summary.coverage)}%</td><td>{fixed(r.summary.meanLatencyMs)} / {fixed(r.summary.p95LatencyMs)} ms</td></tr>)}</tbody></table></div>:<p>No completed comparison for this configuration. No expected results are substituted.</p>}
      <p>Turns count entries into committed turning bouts; collision attempts are rejected translation steps. Coverage counts visited reachable cell centers, not Rescue's visible-area coverage.</p>
    </section>
    {!sim.running&&!comparing?<StimulationLab key={epoch} sim={sim} ready={readiness.state==='ready'}/>:<p className="fly-card">Pause the experiment and finish any comparison to open Experimental Stimulation.</p>}
    <section className="fly-card"><p className="fly-kicker">EVIDENCE REGISTER</p><div className="fly-evidence-grid"><div><span className="fly-evidence real">REAL DATA</span><p>MaleCNS neuron IDs, soma/root laterality and structural contact counts. {readiness.data?`${readiness.data.neurons.toLocaleString()} selected neurons; ${readiness.data.edges.toLocaleString()} connections; ${readiness.data.synaptic_contacts.toLocaleString()} contacts loaded in the shared backend.`:'Live dataset counts unavailable.'}</p></div><div><span className="fly-evidence documented">DOCUMENTED ANNOTATION</span><p>Inputs: class=mechanosensory_tactile and entryNerve=ProLN. Outputs: type=DNa02, selected by somaSide. Annotation identity does not establish the function of this entire model.</p></div><div><span className="fly-evidence inferred">INFERRED</span><p>The functional significance of the selected structural routes for these virtual obstacle responses.</p></div><div><span className="fly-evidence engineering">ENGINEERING MODEL</span><p>Rays, input encoding, normalized weights, simulated activity, body kinematics and DNa02-to-turn decoding. A positive L−R steering rule is not proof of biological causality.</p></div></div></section>
    <section className="fly-card"><p className="fly-kicker">CLOSED-LOOP ARCHITECTURE</p><div className="fly-architecture">Virtual environment → Simulated sensory system → Engineering transduction → Real MaleCNS connectivity → Simulated dynamics → Selected neural readouts → Engineering motor decoder → Virtual body → Environment ↺</div></section>
    <section className="fly-limitations"><div><h2>What this simulation is</h2><p>Real MaleCNS structural connectivity combined with experimental computational models. A reproducible way to inspect a bounded sensory–neural–motor loop.</p></div><div><h2>What this simulation is not</h2><p>A complete fruit-fly brain simulation, a reconstruction of consciousness, measured neural physiology, complete biomechanics, proof that DNa02 activity alone determines turning, or a physical insect-control system.</p></div></section>
  </main>;
}
function NeuralTrace({rows}:{rows:FlyResult['telemetry']}){const data=rows.filter(r=>r.dna02L!==null).slice(-150);if(!data.length)return <p>No neural samples yet. Rule-Based runs do not generate synthetic neural readouts.</p>;const max=Math.max(.001,...data.flatMap(r=>[r.dna02L!,r.dna02R!])),first=data[0].time,last=data.at(-1)!.time;return <svg className="fly-neural-trace" viewBox="0 0 600 160" role="img" aria-label="Actual simulated DNa02 response peaks over experiment time. Left mint, right amber. Auto-scaled.">{[0,.5,1].map(f=><g key={f}><line x1={50} x2={580} y1={125-f*100} y2={125-f*100} stroke="#294255"/><text x={5} y={129-f*100}>{(max*f).toFixed(3)}</text></g>)}{(['dna02L','dna02R'] as const).map((key,i)=><polyline key={key} fill="none" stroke={i?'#f6bf73':'#71dfc6'} strokeWidth={2} points={data.map(r=>`${50+(r.time-first)/Math.max(.2,last-first)*530},${125-r[key]!/max*100}`).join(' ')}/>)}<text x={50} y={150}>{first.toFixed(1)} s</text><text x={540} y={150}>{last.toFixed(1)} s</text></svg>;}
