import type {RescueDiscovery} from '../simulation/rescue';

export const findingTitle=(d:RescueDiscovery)=>d.kind==='gas'?(d.status==='high gas'?'High gas signal':'Gas warning'):d.status==='confirmed'?'Survivor located in simulation':'Possible life signal';
export function MissionFindings({discoveries,selected,onSelect,gasOnly=false}:{discoveries:RescueDiscovery[];selected:string|null;onSelect:(id:string)=>void;gasOnly?:boolean}){
  const finding=discoveries.find(d=>d.id===selected);
  return <section className="mission-findings" aria-label="Observed mission findings">
    <h2>{gasOnly?'Gas hazards':'What have we found?'}</h2><p>{gasOnly?'Reported gas signals. An empty list does not establish that the building is safe.':'Only signals detected by the insects appear here. Unseen people and hazards remain unknown.'}</p>
    {!discoveries.length?<div className="mission-empty"><span aria-hidden="true">◎</span><h3>Waiting for the first signal</h3><p>Start the search. As insects move through accessible gaps, {gasOnly?'nearby simulated gas signals can be detected.':'nearby simulated life and gas signals can be detected.'} Walls can block a reading.</p></div>:<div className="mission-finding-list">{discoveries.map(d=><button key={d.id} aria-pressed={selected===d.id} onClick={()=>onSelect(d.id)}><span className={d.kind==='gas'?'finding-gas':'finding-life'}>{findingTitle(d)}</span><strong>Sector {d.sector}</strong><small>Reported by {d.detectedBy} · {d.observers.length} observer{d.observers.length===1?'':'s'}</small></button>)}</div>}
    {finding&&<div className="mission-finding-detail" role="status"><h3>{findingTitle(finding)} · {finding.sector}</h3><p>{finding.kind==='gas'?'Treat this location as a simulated hazard requiring human assessment. A reading does not prove surrounding areas are safe.':finding.status==='confirmed'?'Sustained strong readings met the simulation’s confirmation rule. This marks a location for human assessment; no person has been extracted.':'A weak or brief signal needs more evidence. The insects must collect sustained strong readings before the simulation confirms it.'}</p><dl><div><dt>Estimated location</dt><dd>{finding.estimatedPosition.x.toFixed(0)}, {finding.estimatedPosition.y.toFixed(0)} world units</dd></div><div><dt>Evidence score</dt><dd>{Math.round(finding.confidence*100)}% · not a medical probability</dd></div><div><dt>Strong-reading confirmation</dt><dd>{finding.confirmedBy.join(', ')||'Not yet'}</dd></div><div><dt>Latest observation</dt><dd>{finding.latestObservation.toFixed(1)} simulated seconds</dd></div></dl></div>}
  </section>;
}
