import {useRef,useState} from 'react';
import Rescue3D from '../components/Rescue3D';
import {EnvironmentCanvas} from '../components/EnvironmentCanvas';
import {MissionFindings} from './MissionFindings';
import {ThermalFindings,ThermalSensor} from './ThermalFindings';
import {SwarmPanel} from '../components/SwarmPanel';
import {CommanderPanel} from '../components/CommanderPanel';
import {ControllerPanel} from '../components/ControllerPanel';
import {AnatomicalPanel} from '../virtual-fly/AnatomicalViewer';
import {useReadiness} from '../hooks/useReadiness';
import {useRescueLab} from './useRescueLab';
import {rescueVisuals} from './visuals';
import type {RescueAppearance} from './visuals';
import {MissionControls,DecisionPanel} from './MissionControls';
import type {BodyStyle} from '../virtual-fly/embodimentModel';
import '../virtual-fly/fly-lab.css';
import './mission.css';
export default function RescueLab(){
  const mission=useRescueLab(),ready=useReadiness();
  const [appearance,setAppearance]=useState<RescueAppearance>({body:'biobug',motion:'walk'});
  const [picking,setPicking]=useState(false);
  const [map,setMap]=useState(false),[discovery,setDiscovery]=useState<string|null>(null),[showAnatomy,setShowAnatomy]=useState(false),[showAI,setShowAI]=useState(false);
  const look=useRef(appearance);look.current=appearance;
  const input=useRef({picking,waypoint:mission.waypoint});input.current={picking,waypoint:mission.waypoint};
  const place=(point:{x:number;y:number})=>{input.current.waypoint(point);setPicking(false);};
  const [visualOptions]=useState(()=>({...rescueVisuals(()=>look.current),isPicking:()=>input.current.picking,onDestination:place}));
  const selected=mission.agents[mission.selected];
  const blocked=mission.mode==='malecns'&&ready.state!=='ready';
  const notices=mission.rescue.events.slice().reverse().map(e=>({time:e.timestamp,title:e.type,sector:e.sector}));
  const reset=(count?:number)=>{mission.reset(count);setDiscovery(null);setPicking(false);};
  const exportReport=()=>{
    const report={...mission.commanderSnapshot(),operations:mission.exportOperations(),scope:'Simulated thermal and gas observations only. Heat cannot confirm a person, animal or life. Location uncertainty uses world units and an illustrative range/localization aid; no physical rescue has occurred.'};
    const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));
    const link=document.createElement('a');link.href=url;link.download='biobug-mission-report.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  };
  return <main className="fly-lab rescue-lab mission-simple">
    <header className="mission-title"><div><p className="fly-kicker">EARTHQUAKE RESPONSE · SIMULATED MISSION</p><h1>Search the collapsed building.</h1><p>Send a small insect team into the rubble. Follow their search, investigate heat signals and map gas hazards.</p></div><span className="mission-state">{mission.running?'Search in progress':mission.elapsed?'Search paused':'Ready to deploy'}</span></header>
    <section className="mission-brief" aria-label="Mission briefing"><div><b>01 · Deploy</b><p>Start with four insects. They explore together and share a map.</p></div><div><b>02 · Observe</b><p>Dim areas are unexplored. Select an insect to follow its progress.</p></div><div><b>03 · Review</b><p>Inspect reported locations. Pause at any time and export findings for review.</p></div></section>
    <div className="mission-commandbar"><button className="fly-primary" disabled={blocked&&!mission.running} onClick={mission.toggle}>{mission.running?'Pause search':mission.elapsed?'Resume search':'Start rescue mission'}</button><button onClick={()=>reset()}>New mission</button><button disabled={!mission.elapsed} onClick={exportReport}>Export findings</button><span>{mission.mode==='malecns'?'MaleCNS obstacle controller':'Automatic exploration'} · {mission.agents.length} insects<br/><small>New mission clears the current run. Pause freezes simulated time.</small></span></div>
    <details className="mission-settings"><summary>Mission settings <span>Team size, controller and appearance</span></summary>
    <section className="fly-config" aria-label="Rescue lab configuration">
      <label>AGENTS<select aria-label="Number of agents" value={mission.agents.length} disabled={mission.running} onChange={e=>reset(Number(e.target.value))}>{[1,2,4,8].map(n=><option key={n} value={n}>{n} BioBug{n===1?'':'s'}</option>)}</select></label>
      <label>BODY STYLE<select aria-label="Rescue body style" value={appearance.body} onChange={e=>setAppearance({...appearance,body:e.target.value as BodyStyle})}><option value="biobug">BioBug / Cyborg Fly</option><option value="natural">Natural Fly</option><option value="simple">Simple / Fallback</option></select></label>

      <div className="fly-mode" role="group" aria-label="Mission controller">{(['rule-based','malecns'] as const).map(mode=><button key={mode} aria-pressed={mission.mode===mode} disabled={mission.running||mode==='malecns'&&ready.state!=='ready'} onClick={()=>mission.controller(mode)}>{mode==='malecns'?'MALECNS':'RULE-BASED'}</button>)}</div>
      <label className="lab-check"><input type="checkbox" checked={mission.coordinated} disabled={mission.running} onChange={e=>mission.coordinate(e.target.checked)}/> COORDINATION</label>
      <p>{ready.state==='ready'?'MaleCNS backend ready.':'MaleCNS backend loading or unavailable; rule-based exploration works offline.'} RULE-BASED follows engineering rules; MALECNS uses a structural connectome with simulated dynamics for obstacle responses. Neither implements smell or vision. Pause to change controller or coordination. Changing team size starts a fresh mission. Coordination helps insects divide exploration. Body style only changes appearance. Takeoff and landing affect altitude and clearance. Radio reports are delayed.</p>
    </section>
    </details>
    <section className="lab-score" aria-label="Rescue lab metrics">{[['WALKABLE FLOOR SEEN',`${mission.explored.toFixed(1)}%`],['HEAT SOURCES',mission.thermal.findings.length],['VERIFIED LIFE','Unverified'],['GAS WARNINGS',mission.rescue.hazards],['SIMULATED TIME',`${Math.floor(mission.elapsed/60)}:${String(Math.floor(mission.elapsed%60)).padStart(2,'0')}`]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>
    <p className="mission-context">Heat is a clue, not proof of life. Warm objects can produce the same reading. Sources that have not been detected are not included in these counts.</p>
    <div className="mission-workspace"><section className="fly-card lab-mission">
      <div className="lab-mission-heading"><div><p className="fly-kicker">EARTHQUAKE / SEED 2026</p><h2>Collapsed structure</h2></div><span>{mission.running?'SEARCH ACTIVE':mission.elapsed?'PAUSED':'READY TO DEPLOY'}</span></div>
      <div className="lab-actions"><button aria-pressed={map} onClick={()=>setMap(!map)}>{map?'View in 3D':'View overhead map'}</button><span className="mission-context">Drag to rotate · scroll to zoom · select an insect below</span></div>
      {!map?<Rescue3D spatialMission picking={picking} onWaypoint={place} key={mission.revision} environment={mission.environment} agents={mission.agents} selected={mission.selected} discoveries={mission.rescue.discoveries} elapsed={mission.elapsed} running={mission.running} onSelect={mission.select} onDiscovery={setDiscovery} onExit={()=>setMap(true)} onToggle={mission.toggle} resumeDisabled={blocked&&!mission.running} visualOptions={visualOptions}/>:<EnvironmentCanvas picking={picking} onWaypoint={place} environment={mission.environment} agents={mission.agents} selected={mission.selected} onSelect={mission.select} discoveries={mission.rescue.discoveries} onDiscovery={setDiscovery} reveal={false} debug={true}/>}
      <div className="lab-discoveries" role="status" aria-live="polite">{notices.length?notices.slice(0,3).map(n=><span key={`${n.time}-${n.title}-${n.sector}`}><b>{n.title}</b> · Sector {n.sector} · {n.time.toFixed(1)} s</span>):<span>No observations yet. Heat and gas markers appear only after sensing. HEAT ? is an uncertain location, not a confirmed survivor.</span>}</div>
    </section><aside className="mission-desk"><div className="mission-selected"><label>Follow an insect<select aria-label="Inspected agent" value={mission.selected} onChange={e=>mission.select(Number(e.target.value))}>{mission.agents.map((a,i)=><option value={i} key={a.bug.id}>{a.bug.id}</option>)}</select></label><p><b style={{color:selected.color}}>{selected.bug.id}</b> · {mission.running?selected.bug.state:'paused'}<br/>{!mission.running?'Waiting for you to start or resume the search.':selected.bug.state==='blocked'?'Adjusting its route around an obstacle or another insect.':'Searching accessible areas and sharing observations.'}</p><MissionControls operation={mission.operation} running={mission.running} picking={picking} onPick={()=>setPicking(!picking)} command={mission.command} steer={mission.steer} link={mission.link}/><ThermalSensor reading={mission.thermal.reading} running={mission.running}/><p>Gas signal: {Math.round(mission.rescue.reading.gas*100)}%<small>Simulated sensor strength, not a probability.</small></p>{mission.rescue.reading.exposed&&<p role="alert" className="fly-error">This insect is sensing high gas.</p>}</div><ThermalFindings findings={mission.thermal.findings} selected={discovery} onSelect={setDiscovery} elapsed={mission.elapsed}/><section className="mission-controls"><h3>Investigate reported heat</h3><p>Choose a HEAT ? finding, then request another viewpoint. A free insect is assigned; a different observer is preferred.</p><button disabled={!discovery?.startsWith('T-')} onClick={()=>discovery&&mission.investigate(discovery)}>Investigate {discovery?.startsWith('T-')?discovery:'selected heat'}</button>{mission.operation.investigations.map(t=><p key={t.id}><b>{t.findingId} · {t.agentId}</b><br/>{t.status} — {t.message}</p>)}<p className="mission-context">Repeated warmth never establishes a person, animal or life. Report matching uses a simplified simulation association, not real thermal tracking.</p></section><DecisionPanel sample={mission.operation.explanation} age={mission.operation.age}/><MissionFindings gasOnly discoveries={mission.rescue.discoveries.filter(d=>d.kind==='gas')} selected={discovery} onSelect={setDiscovery}/></aside></div>
    {mission.neural.status==='offline'&&<p className="fly-error" role="alert">{mission.neural.error} Mission paused. Retry Resume or choose Rule-Based.</p>}
    <section className="mission-explanation" aria-label="How this mission works"><h2>What is the insect actually doing?</h2><div><article><h3>Finding a way through</h3><p>Obstacle sensors, collision checks and shared-map planning guide the team. In MaleCNS mode, simulated activity on a real 295-neuron structural circuit contributes steering proposals.</p></article><article><h3>Detecting a person or gas</h3><p>A simulated thermal sensor detects surface warmth inside its forward view. Walls, debris, range and low contrast can hide sources. Warm objects cause detections too; repeated heat never confirms a survivor. Gas is sensed separately. Biological smell and vision are not implemented.</p></article><article><h3>Your role as operator</h3><p>Start or pause the search, select an insect, inspect findings and export a report. Choose a revealed destination, take temporary steering control, request takeoff or landing, and return to autonomous exploration. Use another insect to investigate reported heat.</p></article></div><p className="mission-context">This is a rescue research simulation. Flight uses simulated altitude: it can cross low debris but cannot cross tall walls or ceiling slabs. This is a simplified collision and motion model, not realistic insect aerodynamics. Detection, battery, radio and actuation settings are engineering assumptions. No physical extraction is simulated.</p></section>
    <section className="mission-neurons"><div className="mission-section-heading"><div><h2>See the neural activity</h2><p>Inspect the selected insect’s controller. Real MaleCNS structure; simulated activity.</p></div><button aria-expanded={showAnatomy} onClick={()=>setShowAnatomy(!showAnatomy)}>{showAnatomy?'Hide neural activity':'Show neural activity'}</button></div>{showAnatomy&&<>
      <div className="lab-actions" aria-label="Neural activity controls">
        {mission.mode!=='malecns'?<button disabled={mission.running||ready.state!=='ready'} onClick={()=>mission.controller('malecns')}>Use MaleCNS controller</button>:<button disabled={blocked&&!mission.running} onClick={mission.toggle}>{mission.running?'Pause neural run':'Run MaleCNS activity'}</button>}
        <span>{mission.mode!=='malecns'?(mission.running?'Pause the search before switching controllers.':ready.state==='ready'?'Backend ready. Switch to MaleCNS, then run to see neuron activity.':'Neural backend is loading or unavailable. Start the Python backend on port 8000.'):'Neural colors follow received accepted controller samples. Radio loss holds the overlay; operator control bypasses new evaluations.'}</span>
      </div>
      <p><b>Observed body state:</b> {mission.running?selected.bug.state:'paused'} · <b>Movement arbitration:</b> {selected.coordination}. Neural output is a steering proposal; shared-map guidance and collision checks can change the resulting movement.</p>
      <p className="mission-context">{mission.mode==='malecns'?'Colors reflect accepted controller samples. Pausing holds the last sample.':'Automatic exploration uses rules. Choose MALECNS in Mission settings to generate neural activity; this view currently shows structure only.'} Thermal and gas sensing use separate engineering models, not smell, vision or thermosensory neurons in this MaleCNS circuit.</p><AnatomicalPanel neuralSuspended={mission.neuralSuspended} sim={mission.anatomy} history={mission.history} sourceLabel={`Collapsed building rescue · ${selected.bug.id}`} actionLabel="NEURAL MOTOR PROPOSAL"/></>}</section>
    <section className="mission-assistant"><div className="mission-section-heading"><div><h2>Need help interpreting the mission?</h2><p>The optional AI assistant summarizes observed findings. It cannot move insects or verify a real survivor.</p></div><button aria-expanded={showAI} onClick={()=>setShowAI(!showAI)}>{showAI?'Close assistant':'Open mission assistant'}</button></div>{showAI&&<CommanderPanel key={mission.revision} compact getSnapshot={mission.commanderSnapshot}/>}</section>
    <details className="mission-settings"><summary>Research details <span>Team telemetry and motor decoding</span></summary><SwarmPanel view={mission} onSelect={mission.select}/><ControllerPanel view={mission}/></details>
    <details className="mission-settings"><summary>Operator and simulation diagnostics</summary><p>Diagnostics include onboard events even during radio loss; map, findings and task reports show received packets only.</p><ol className="mission-log">{mission.operation.events.map((e,i)=><li key={i}><time>{e.time.toFixed(1)} s</time><span>{e.agentId} · {e.text}</span></li>)}</ol></details>
    <details className="mission-settings"><summary>Mission event log <span>{mission.rescue.events.length} recorded events</span></summary>{mission.rescue.events.length?<ol className="mission-log">{mission.rescue.events.slice().reverse().map((e,i)=><li key={i}><time>{e.timestamp.toFixed(1)} s</time><span>{e.type} · Sector {e.sector}<small>{e.bugId}</small></span></li>)}</ol>:<p>No detections yet. Events will appear as the insects search.</p>}</details>
  </main>;
}
