import type {ThermalFinding,ThermalReading} from './thermal';
import {THERMAL} from './thermal';

export function ThermalSensor({reading,running}:{reading:ThermalReading;running:boolean}){
  return <div className="thermal-sensor" aria-label="Selected insect thermal sensor"><b>Simulated thermal sensor</b><p>{running?'Latest sampled view':'Paused · last sampled view'} · {reading.visibleSpots} detectable heat spot{reading.visibleSpots===1?'':'s'}</p><div className="thermal-temperature">{reading.apparentC===null?'—':`${reading.apparentC.toFixed(1)} °C`}<small>strongest spot · apparent surface temperature</small></div><meter min="0" max="1" value={reading.signal} aria-label="Thermal signal strength"/><p>{Math.round(reading.signal*100)}% signal · ambient {THERMAL.ambientC} °C<br/>120° forward view · up to {THERMAL.range} world units</p><small>Walls and debris block views. No heat reading does not prove an area is empty. Values are illustrative, not calibrated hardware measurements.</small></div>;
}
export function ThermalFindings({findings,selected,onSelect,elapsed}:{findings:ThermalFinding[];selected:string|null;onSelect:(id:string)=>void;elapsed:number}){
  const d=findings.find(f=>f.id===selected);
  return <section className="mission-findings" aria-label="Thermal observations"><h2>Heat to investigate</h2><p>Heat may come from a person, an animal or a warm object. Identity and signs of life remain unverified.</p>
    {!findings.length?<div className="mission-empty"><h3>No heat observed yet</h3><p>Search gaps with a clear view. Warm equipment is included in this scenario and can trigger the same sensor.</p></div>:<div className="mission-finding-list">{findings.map(f=><button key={f.id} aria-pressed={selected===f.id} onClick={()=>onSelect(f.id)}><span className="finding-heat">{f.id} · Unidentified heat</span><strong>Sector {f.sector}</strong><small>{f.persistent?'Repeated readings · still unverified':'Initial reading · unverified'}<br/>Last seen {Math.max(0,elapsed-f.latestObservation).toFixed(1)} s ago · ±{f.uncertaintyRadius} world units</small></button>)}</div>}
    {d&&<div className="mission-finding-detail" role="status"><h3>{d.id} · Identity unknown</h3><p>Human verification required. Repeated heat does not confirm a person, animal, heartbeat or survival.</p><svg className="thermal-location" viewBox="0 0 260 120" role="img" aria-label={`Estimated location uncertainty radius ${d.uncertaintyRadius} world units. Schematic, not a map.`}><circle cx="65" cy="60" r="44" fill="#dcb27718" stroke="#eac184" strokeDasharray="5 4"/><circle cx="65" cy="60" r="4" fill="#f3d698"/><path d="M65 60H109" stroke="#eac184"/><text x="122" y="55">±{d.uncertaintyRadius} world units</text><text x="122" y="75">search radius · schematic</text></svg><dl><div><dt>Estimated position</dt><dd>{d.estimatedPosition.x.toFixed(0)}, {d.estimatedPosition.y.toFixed(0)} world units</dd></div><div><dt>Location uncertainty</dt><dd>±{d.uncertaintyRadius} world units · model bound, not a statistical confidence interval</dd></div><div><dt>Apparent surface temperature</dt><dd>{d.apparentC.toFixed(1)} °C · {d.contrastC.toFixed(1)} °C above ambient</dd></div><div><dt>Observations</dt><dd>{d.observations} · {d.observers.join(', ')}</dd></div><div><dt>First / latest seen</dt><dd>{d.firstDetected.toFixed(1)} / {d.latestObservation.toFixed(1)} s</dd></div><div><dt>Observation age</dt><dd>{Math.max(0,elapsed-d.latestObservation).toFixed(1)} simulated seconds · historical location</dd></div></dl><p>Coordinates use a simulated range and positioning aid with injected error. A thermal camera alone does not provide this location. The map marker is the estimate’s center.</p></div>}
  </section>;
}
