const assert=require('node:assert/strict'),fs=require('node:fs');
const load=require('../scripts/compile_unified_lab.cjs')();
const {anatomyPresentation:present}=load('virtual-fly/anatomyPresentation');
const {AnatomicalHistory}=load('virtual-fly/anatomicalTelemetry');
const manifest=JSON.parse(fs.readFileSync('public/malecns/manifest.json','utf8'));
const state=()=>({config:{mode:'malecns'},running:true,elapsed:2,neural:{status:'ready'},fly:{turning:'FORWARD'}});
const history=()=>{const h=new AnatomicalHistory();h.ids=manifest.neurons.map(n=>n.body_id);h.graph=manifest.graph_sha256;h.samples=[{time:1,sequence:1,values:h.ids.map((_,i)=>i===0?.5:0)}];return h;};
let passed=0;function test(name,fn){fn();passed++;console.log('PASS',name);}
test('live values preserve exact ID association without mutating state or samples',()=>{const s=state(),h=history(),before=JSON.stringify({s,h});const p=present(s,h,manifest);assert.equal(p.status,'LIVE / SAMPLED');assert.equal(p.active,1);assert.equal(p.values[h.ids[0]],.5);assert.equal(JSON.stringify({s,h}),before);});
test('manual control and offline override a misleading live/paused badge',()=>{const s=state(),h=history();assert.equal(present(s,h,manifest,'',true).status,'HISTORICAL / OPERATOR');s.running=false;s.neural.status='offline';assert.equal(present(s,h,manifest).status,'OFFLINE / LAST SAMPLE');assert.deepEqual(present(s,h,manifest).values,present(state(),h,manifest).values);});
test('paused and pending evaluations retain explicitly held samples',()=>{const s=state(),h=history();s.running=false;assert.equal(present(s,h,manifest).status,'PAUSED / LAST SAMPLE');s.running=true;for(const status of ['idle','waiting']){s.neural.status=status;assert.equal(present(s,h,manifest).status,'WAITING / LAST SAMPLE');}});
test('fresh/reset trial never claims live activity',()=>{const s=state(),h=new AnatomicalHistory();assert.equal(present(s,h,manifest).status,'AWAITING FIRST SAMPLE');s.running=false;assert.equal(present(s,h,manifest).status,'PAUSED / NO SAMPLE');assert.deepEqual(present(s,h,manifest).values,{});});
test('rule-based mode suppresses retained neural samples',()=>{const s=state();s.config.mode='rule-based';const p=present(s,history(),manifest);assert.equal(p.status,'STRUCTURE ONLY');assert.equal(p.sample,undefined);assert.deepEqual(p.values,{});});
test('graph and neuron identity mismatch disable overlays',()=>{for(const change of [h=>h.graph='different',h=>h.ids[0]='999999999']){const h=history();change(h);const p=present(state(),h,manifest);assert.equal(p.status,'IDENTITY MISMATCH');assert.equal(p.enabled,false);assert.deepEqual(p.values,{});}});
test('missing or failed geometry never claims live activity',()=>{assert.equal(present(state(),history(),null).status,'VERIFYING STRUCTURE');const p=present(state(),history(),manifest,'WebGL lost');assert.equal(p.status,'VIEWER UNAVAILABLE');assert.deepEqual(p.values,{});});
test('agent selection replaces overlay instead of merging histories; zero stays zero',()=>{const a=history(),b=history();b.samples[0].values.fill(0);assert.equal(present(state(),a,manifest).active,1);assert.equal(present(state(),b,manifest).active,0);assert.equal(present(state(),a,manifest).active,1);});
test('headline never advertises live activity for a structure-only or held sample',()=>{const s=state(),h=history();assert(present(s,h,manifest).headline.startsWith('LIVE'));s.running=false;assert(present(s,h,manifest).headline.startsWith('RECORDED'));s.config.mode='rule-based';const p=present(s,h,manifest);assert(p.headline.includes('NO ACTIVITY'));assert(p.explanation.includes('Rule-based'));s.config.mode='malecns';s.running=true;s.neural.status='offline';assert(!present(s,h,manifest).headline.startsWith('LIVE'));assert(present(s,h,manifest).explanation.includes('not changing live'));});
console.log(`${passed} anatomical presentation checks passed`);
