const assert=require('node:assert/strict');
const load=require('../scripts/compile_virtual_fly.cjs')();
const {createFly,runFly,advanceFly,acceptFlyNeural,flyResult,FLY_STEP}=load('virtual-fly/simulation');
const {DEFAULT_EXPERIMENT}=load('virtual-fly/experiments');
const {parseAnatomicalResponse,anatomyHistory,AnatomicalHistory}=load('virtual-fly/anatomicalTelemetry');
const {stepFlyDecision}=load('virtual-fly/step');
const {validateManifest,visibleNeuron}=load('virtual-fly/anatomyModel');
const {CONTROL_MODEL}=load('simulation/neuralClient');
const {mapSensors}=load('simulation/sensorMapping');
const manifest=require('../public/malecns/manifest.json');
const ids=manifest.neurons.map(n=>n.body_id);
// Synthetic transport fixture only. The separate live comparison uses the real backend.
function response(input){const values=ids.map(()=>.01);values[ids.indexOf('523769')]=input.left*.2+input.front*.04;values[ids.indexOf('10360')]=input.right*.2+input.front*.04;
return {dataset:'MaleCNS',version:'v1.0',model:CONTROL_MODEL,stimulus:{...input},structural_unchanged:true,graph:{neurons:295,edges:280,structural_contacts:2308,structural_sha256:manifest.graph_sha256},dna02:{L:{id:'523769',side_field:'somaSide',peak:values[ids.indexOf('523769')]},R:{id:'10360',side_field:'somaSide',peak:values[ids.indexOf('10360')]}},input_active:0,top_intermediate_types:[],evaluation_seconds:0,activity:{statistic:'peak-over-20-steps-from-rest',body_ids:ids.slice(),values}};}
const tests=[];const test=(n,f)=>tests.push([n,f]);const config={...DEFAULT_EXPERIMENT,mode:'malecns',experiment:'front',duration:3};
test('Activity parsing rejects duplicates, missing values and inconsistent motor peaks',()=>{const input={left:1,front:0,right:0};assert.equal(parseAnatomicalResponse(response(input),input).activity.values.length,295);for(const corrupt of [r=>r.activity.body_ids[0]=r.activity.body_ids[1],r=>r.activity.values.pop(),r=>r.activity.values[0]=NaN,r=>r.activity.values[ids.indexOf('523769')]=.9,r=>delete r.activity]){const r=response(input);corrupt(r);assert.throws(()=>parseAnatomicalResponse(r,input));}});
test('Manifest rejects invalid offsets, incomplete coverage and altered units',()=>{validateManifest(manifest);for(const corrupt of [m=>m.neurons[0].segment_offset++,m=>m.available--,m=>m.transform.scale=1,m=>m.neurons[1].body_id=m.neurons[0].body_id]){const m=structuredClone(manifest);corrupt(m);assert.throws(()=>validateManifest(m));}});
test('Population and active filters exclude missing geometry and unmeasured activity',()=>{const n=manifest.neurons.find(n=>n.population==='DNa02');assert(visibleNeuron(n,'DNa02',false,null));assert(!visibleNeuron(n,'ProLN',false,.5));assert(!visibleNeuron(n,'all',true,null));assert(!visibleNeuron(n,'all',true,0));assert(visibleNeuron(n,'all',true,.01));assert(!visibleNeuron({...n,available:false},'all',false,1));});
test('Observer is immutable, deduplicates samples, freezes on pause and bounds history',()=>{const s=createFly(config),h=anatomyHistory(s);runFly(s,true);for(let i=0;i<200;i++){acceptFlyNeural(s,response(mapSensors(s.fly.sensors)),0);const before=JSON.stringify(s);h.observe(s);h.observe(s);assert.equal(JSON.stringify(s),before);}assert.equal(h.samples.length,180);runFly(s,false);const frozen=JSON.stringify(h.samples);for(let i=0;i<20;i++){advanceFly(s,FLY_STEP);h.observe(s);}assert.equal(JSON.stringify(h.samples),frozen);assert.equal(anatomyHistory(createFly(config)).samples.length,0);const old=h.samples.at(-1).values[0];s.neural.response.activity.values[0]=.9;assert.equal(h.samples.at(-1).values[0],old);});
test('Viewer OFF/ON observer paths produce identical complete simulation results',()=>{function trial(on){const s=createFly(config),h=new AnatomicalHistory();runFly(s,true);while(!s.completed){if(s.ticks>=s.neural.nextTick)acceptFlyNeural(s,response(mapSensors(s.fly.sensors)),0);if(on)h.observe(s);advanceFly(s,FLY_STEP);}return flyResult(s);}assert.deepEqual(trial(false),trial(true));});
test('Step uses one evaluation and twelve existing physics ticks, then freezes',async()=>{const s=createFly(config),h=anatomyHistory(s);let count=0;await stepFlyDecision(s,()=>s,async input=>{count++;return response(input);},new AbortController().signal,()=>h.observe(s));assert.equal(count,1);assert.equal(s.ticks,12);assert.equal(s.elapsed,.2);assert.equal(s.metrics.samples,1);assert.equal(h.samples.length,1);assert(!s.running);const result=flyResult(s);advanceFly(s,1);assert.deepEqual(flyResult(s),result);await stepFlyDecision(s,()=>s,async input=>response(input),new AbortController().signal,()=>h.observe(s));assert.equal(s.ticks,24);assert.equal(h.samples.length,2);});
test('Failed or timed-out step holds physics and reports an explicit error',async()=>{for(const timeout of [false,true]){const s=createFly(config),abort=new AbortController();await stepFlyDecision(s,()=>s,async()=>{if(timeout)abort.abort();throw Error('test offline');},abort.signal);assert.equal(s.ticks,0);assert.equal(s.neural.status,'offline');assert(s.neural.error);assert(!s.running);}});
test('Reset during pending step discards the obsolete response',async()=>{const s=createFly(config);let current=s,resolve;const pending=stepFlyDecision(s,()=>current,input=>new Promise(r=>resolve=()=>r(response(input))),new AbortController().signal);current=createFly(config);resolve();await pending;assert.equal(current.metrics.samples,0);assert.equal(s.metrics.samples,0);});
(async()=>{for(const [name,fn]of tests){await fn();console.log('PASS',name);}console.log(`${tests.length} anatomical viewer checks passed`);})().catch(e=>{console.error(e);process.exitCode=1;});
