const fs=require('node:fs'),assert=require('node:assert/strict');
const load=require('./compile.cjs')();
const {createSwarm,runSwarm,advanceSwarm,swarmSnapshot,switchSwarm}=load('swarm');
const {createRescueMission,sampleRescue,rescueView,observation,signalStrength,sector}=load('rescue');
const {isPositionValid,canTravel}=load('collision');
const {accessibleCells,cellCenter}=load('exploration');
const tests=[];function test(name,fn){tests.push([name,fn]);}
function fixture(){const s=createSwarm(2),env=s.agents[0].simulation.environment;env.obstacles=[];const m=createRescueMission(env);m.targets=[{id:'test-life',kind:'life',groundTruthPosition:{x:400,y:280}}];const bugs=s.agents.map(a=>({...a.simulation.bug,position:{x:380,y:280},heading:.1}));return {env,m,bugs};}
function tick(f,t){sampleRescue(f.m,f.env,f.bugs,t);}
test('signals are bounded, monotonic and use independent radii',()=>{assert.equal(signalStrength(0,85),1);assert.equal(signalStrength(85,85),0);assert.equal(signalStrength(500,85),0);assert(signalStrength(20,85)>signalStrength(40,85));const f=fixture();tick(f,.25);assert(f.m.readings[f.bugs[0].id].life>0);assert.equal(f.m.readings[f.bugs[0].id].gas,0);f.m.targets[0].kind='gas';tick(f,.5);assert.equal(f.m.readings[f.bugs[0].id].life,0);assert(f.m.readings[f.bugs[0].id].gas>0);});
test('weak readings below threshold cannot reveal targets even with all fog explored',()=>{const f=fixture();f.env.exploration.explored.fill(true);f.bugs.forEach(b=>b.position={x:325,y:280});tick(f,.25);assert.equal(f.m.discoveries.length,0);const s=createSwarm();s.agents[0].simulation.environment.exploration.explored.fill(true);const view=swarmSnapshot(s);assert.deepEqual(view.environment.survivors,[]);assert.deepEqual(view.environment.hazards,[]);assert.equal(view.rescue.discoveries.length,0);assert(!JSON.stringify(view.rescue).includes('groundTruthPosition'));});
test('line of sight blocks both rescue channels through a wall',()=>{const f=fixture();f.env.obstacles=[{id:'test-wall',kind:'wall',x:390,y:240,width:5,height:80}];assert.equal(observation(f.env,f.bugs[0],f.m.targets[0]).signal,0);f.m.targets[0].kind='gas';assert.equal(observation(f.env,f.bugs[0],f.m.targets[0]).signal,0);});
test('one agent needs three consecutive strong samples; an interruption resets the streak',()=>{const f=fixture();f.bugs=f.bugs.slice(0,1);tick(f,.25);assert.equal(f.m.discoveries[0].status,'possible');tick(f,.5);assert.equal(f.m.discoveries[0].status,'possible');f.bugs[0].position.x=300;tick(f,.75);f.bugs[0].position.x=380;tick(f,1);tick(f,1.25);assert.equal(f.m.discoveries[0].status,'possible');tick(f,1.5);assert.equal(f.m.discoveries[0].status,'confirmed');assert.equal(f.m.completedAt,1.5);});
test('weak detections cannot accumulate into confirmation',()=>{const f=fixture();f.bugs.forEach(b=>b.position.x=340);for(let i=1;i<=16;i++)tick(f,i*.25);assert.equal(f.m.discoveries[0].status,'possible');assert.equal(f.m.completedAt,null);});
test('multiple agents independently confirm and increase confidence without duplicate event spam',()=>{const f=fixture();f.bugs[1].position.x=200;tick(f,.25);const confidence=f.m.discoveries[0].confidence;tick(f,.5);tick(f,.75);f.bugs[1].position.x=375;tick(f,1);tick(f,1.25);tick(f,1.5);const d=f.m.discoveries[0];assert.equal(d.confirmedBy.length,2);assert(d.confidence>confidence);assert.equal(f.m.events.filter(e=>e.type==='INDEPENDENT SURVIVOR CONFIRMATION').length,1);for(let i=7;i<30;i++)tick(f,i*.25);assert.equal(f.m.events.length,3);});
test('localization, event snapshots and public view do not alias ground truth',()=>{const f=fixture();tick(f,.25);const d=f.m.discoveries[0],original={...f.m.targets[0].groundTruthPosition};assert.notDeepEqual(d.estimatedPosition,original);assert.notStrictEqual(d.estimatedPosition,f.m.targets[0].groundTruthPosition);const eventPosition={...f.m.events[0].estimatedPosition};f.bugs[0].position.x=365;tick(f,.5);assert.deepEqual(f.m.targets[0].groundTruthPosition,original);assert.deepEqual(f.m.events[0].estimatedPosition,eventPosition);const v=rescueView(f.m,f.bugs[0].id);v.discoveries[0].estimatedPosition.x=0;assert.notEqual(d.estimatedPosition.x,0);});
test('strong gas shows current exposure and sustained high concentration',()=>{const f=fixture();f.m.targets[0].kind='gas';tick(f,.25);assert(f.m.readings[f.bugs[0].id].exposed);assert.equal(f.m.discoveries[0].status,'gas warning');tick(f,.5);tick(f,.75);assert.equal(f.m.discoveries[0].status,'high gas');f.bugs.forEach(b=>b.position.x=200);tick(f,1);assert(!f.m.readings[f.bugs[0].id].exposed);assert.equal(f.m.discoveries.length,1);});
test('sector conversion handles boundaries and corners',()=>{assert.equal(sector({x:0,y:0}),'A1');assert.equal(sector({x:200,y:140}),'B2');assert.equal(sector({x:800,y:560}),'D4');assert.equal(sector({x:-5,y:-5}),'A1');});
test('scenario has two reachable life and two gas targets away from deployment',()=>{const s=createSwarm(),env=s.agents[0].simulation.environment,accessible=accessibleCells(env,7);assert.equal(s.rescue.targets.filter(t=>t.kind==='life').length,2);assert.equal(s.rescue.targets.filter(t=>t.kind==='gas').length,2);for(const t of s.rescue.targets){const p=t.groundTruthPosition;assert(isPositionValid(env,p,7));assert(Math.hypot(p.x-env.entry.x,p.y-env.entry.y)>150);assert(accessible.some((valid,i)=>valid&&Math.hypot(cellCenter(env,i).x-p.x,cellCenter(env,i).y-p.y)<25&&canTravel(env,cellCenter(env,i),p,7)));}});
test('demo repeats at different frame rates with collision safety and full reset',()=>{function run(hz){const s=createSwarm();runSwarm(s,true);for(let i=0;i<30*hz;i++){advanceSwarm(s,1/hz);for(const a of s.agents){assert(isPositionValid(a.simulation.environment,a.simulation.bug.position,7));for(const b of s.agents)if(a!==b)assert(Math.hypot(a.simulation.bug.position.x-b.simulation.bug.position.x,a.simulation.bug.position.y-b.simulation.bug.position.y)>=14.249999);}}return s;}const a=run(60),b=run(30);assert.deepEqual(a.rescue,b.rescue);assert.equal(swarmSnapshot(a).rescue.confirmed,2);assert.equal(swarmSnapshot(a).rescue.hazards,2);assert(a.rescue.completedAt<30);assert(new Set(a.rescue.events.map(e=>e.bugId)).size>=2);runSwarm(a,false);const paused=JSON.stringify(a.rescue);advanceSwarm(a,1);assert.equal(JSON.stringify(a.rescue),paused);switchSwarm(a,'malecns');assert.equal(JSON.stringify(a.rescue),paused);const fresh=createSwarm();assert.equal(fresh.rescue.events.length,0);assert.equal(fresh.rescue.discoveries.length,0);assert.equal(fresh.rescue.completedAt,null);assert.deepEqual(fresh.rescue.readings,{});});
test('terrain renderer cannot expose targets even in inspection view',()=>{const ts=require('typescript');const source=fs.readFileSync('src/rendering/drawEnvironment.ts','utf8');const mod={exports:{}};new Function('exports',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(mod.exports);const texts=[];const ctx=new Proxy({fillText:t=>texts.push(t)},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});mod.exports.drawEnvironment(ctx,createSwarm().agents[0].simulation.environment,true);assert(!texts.some(t=>/S-0|H-0|GAS|POSSIBLE/.test(t)));});
for(const [name,fn]of tests){fn();console.log('PASS',name);}console.log(`${tests.length} rescue checks passed`);
