const assert=require('node:assert/strict');
const load=require('../scripts/compile_unified_lab.cjs')();
const M=load('unified-lab/rescueMission'),P=load('unified-lab/space'),{BACKPACK}=load('unified-lab/operations'),{MissionNeuralLoop}=load('unified-lab/missionNeural');
const {rescueVisuals}=load('unified-lab/visuals'),{CONTROL_MODEL}=load('simulation/neuralClient');
const tests=[],test=(n,f)=>tests.push([n,f]);
const step=(s,seconds)=>{for(let i=0;i<Math.round(seconds*60);i++)M.advanceMission(s,1/60);};
function open(count=1){const s=M.createRescueLab(count,2026,false);s.environment.obstacles=[];s.environment.exploration.explored.fill(true);s.ops.forEach((o,i)=>{const sim=s.world.agents[i].simulation;sim.environment.obstacles=[];sim.environment.exploration.explored.fill(true);sim.bug.position={x:100+i*100,y:100};sim.bug.heading=0;o.localHeat.sources=[];});M.runMission(s,true);return s;}
function response(stimulus){return {dataset:'MaleCNS',version:'v1.0',model:CONTROL_MODEL,stimulus,structural_unchanged:true,graph:{neurons:2,edges:1,structural_contacts:3,structural_sha256:'a'.repeat(64)},dna02:{L:{id:'523769',side_field:'somaSide',peak:.1},R:{id:'10360',side_field:'somaSide',peak:.07}},input_active:1,top_intermediate_types:[],evaluation_seconds:0,activity:{statistic:'peak-over-20-steps-from-rest',body_ids:['523769','10360'],values:[.1,.07]}};}
const obstacle=(kind,base=0,height=kind==='wall'?52:18)=>({id:'test',kind,x:150,y:60,width:30,height:100,baseAltitude:base,elevation:height});
test('Walking cannot cross debris; cruise flight clears debris but never tall walls or overhead ceilings',()=>{const s=open(),env=s.environment;env.obstacles=[obstacle('debris')];assert(!P.travel3D(env,{x:100,y:100},3,{x:200,y:100},3,7));assert(P.travel3D(env,{x:100,y:100},28,{x:200,y:100},28,7));env.obstacles=[obstacle('wall')];assert(!P.travel3D(env,{x:100,y:100},28,{x:200,y:100},28,7));env.obstacles=[obstacle('debris',20,8)];assert(!P.travel3D(env,{x:160,y:100},3,{x:160,y:100},28,7));assert(P.travel3D(env,{x:100,y:100},3,{x:100,y:100},28,7));env.obstacles=[obstacle('wall')];assert(!P.groundVisible(env,{x:100,y:100},28,{x:200,y:100}));});
test('Takeoff and landing change altitude continuously; occupied landing sites are rejected',()=>{const s=open();M.issueCommand(s,0,{kind:'operator'});M.issueCommand(s,0,{kind:'flight'});step(s,.3);assert.equal(s.ops[0].altitude,3);step(s,2);assert.equal(s.ops[0].altitude,28);const bug=s.world.agents[0].simulation.bug;s.world.agents[0].simulation.environment.obstacles=[{...obstacle('debris'),x:bug.position.x-10,y:bug.position.y-10,width:20,height:20}];M.issueCommand(s,0,{kind:'land'});step(s,.5);assert.equal(s.ops[0].targetAltitude,28);assert(s.events.some(e=>e.text.startsWith('Landing rejected')));s.world.agents[0].simulation.environment.obstacles=[];M.issueCommand(s,0,{kind:'land'});step(s,2);assert.equal(s.ops[0].altitude,3);});
test('Delayed operator steering expires, cannot persist across pause or radio loss, and autonomy can resume',()=>{const s=open();M.issueCommand(s,0,{kind:'operator'});step(s,.3);assert.equal(s.ops[0].authority,'explore');step(s,.1);assert.equal(s.ops[0].authority,'operator');M.issueCommand(s,0,{kind:'manual',forward:1,angular:0});step(s,.7);assert(s.ops[0].speed>0);M.setMissionLink(s,0,false);const pos={...s.world.agents[0].simulation.bug.position};step(s,1);assert.deepEqual(s.world.agents[0].simulation.bug.position,pos);assert(!M.issueCommand(s,0,{kind:'explore'}));M.setMissionLink(s,0,true);M.issueCommand(s,0,{kind:'manual',forward:1,angular:0});M.runMission(s,false);M.runMission(s,true);step(s,1);assert.equal(s.ops[0].speed,0);M.issueCommand(s,0,{kind:'explore'});step(s,.5);assert.equal(s.ops[0].authority,'explore');});
test('Manual pulses cease after their lease even while radio remains connected',()=>{const s=open();M.issueCommand(s,0,{kind:'operator'});step(s,.5);M.issueCommand(s,0,{kind:'manual',forward:1,angular:0});step(s,1.5);const pos={...s.world.agents[0].simulation.bug.position};step(s,.5);assert.deepEqual(s.world.agents[0].simulation.bug.position,pos);});
test('Radio loss freezes public pose, sensors, map, reports and neural history; reconnect delivers later',()=>{const s=open();M.setMissionLink(s,0,false);const before=M.rescueLabView(s),report=M.rescueLabSnapshot(s);s.ops[0].localHeat.sources=[{key:'hidden',position:{x:165,y:100},surfaceC:36}];step(s,2);const after=M.rescueLabView(s);assert.notDeepEqual(s.world.agents[0].simulation.bug.position,before.agents[0].bug.position);assert.deepEqual(after.agents[0],before.agents[0]);assert.deepEqual(after.thermal.findings,[]);assert.deepEqual(M.rescueLabSnapshot(s).agents,report.agents);assert(s.ops[0].localHeat.findings.length>0);M.setMissionLink(s,0,true);step(s,.2);assert.deepEqual(M.rescueLabView(s).thermal.findings,[]);step(s,.3);assert(M.rescueLabView(s).thermal.findings.length>0);});
test('Backpack battery drains only in simulated time, warns at reserve and holds at exhaustion',()=>{const s=open();s.ops[0].battery=BACKPACK.reserve+.001;step(s,.1);assert(s.ops[0].lowBattery);M.runMission(s,false);const battery=s.ops[0].battery;M.advanceMission(s,30);assert.equal(s.ops[0].battery,battery);s.ops[0].battery=.001;M.runMission(s,true);step(s,.2);assert.equal(s.ops[0].battery,0);assert.equal(s.ops[0].authority,'hold');const pos={...s.world.agents[0].simulation.bug.position};step(s,.5);assert.deepEqual(s.world.agents[0].simulation.bug.position,pos);});
test('Waypoint routing rejects unknown or solid targets and stops at a revealed destination',()=>{const s=open(),env=s.world.agents[0].simulation.environment;env.exploration.explored.fill(false);M.issueCommand(s,0,{kind:'waypoint',target:{x:180,y:100}});step(s,.4);assert.notEqual(s.ops[0].authority,'waypoint');env.exploration.explored.fill(true);M.issueCommand(s,0,{kind:'waypoint',target:{x:180,y:100}});step(s,8);assert.equal(s.ops[0].authority,'waypoint');assert(Math.hypot(s.world.agents[0].simulation.bug.position.x-180,s.world.agents[0].simulation.bug.position.y-100)<8);});
test('Investigation assigns another available insect and reports unverified re-observation only after packets',()=>{const s=open(2);s.ops[0].localHeat.sources=[{key:'warm-object',position:{x:165,y:100},surfaceC:36}];step(s,1);const f=s.thermal.findings[0];assert(f);assert.deepEqual(f.observers,[s.world.agents[0].simulation.bug.id]);assert(M.investigateHeat(s,f.id));assert.equal(s.investigations[0].agentId,s.world.agents[1].simulation.bug.id);assert(!M.investigateHeat(s,f.id));step(s,.5);const o=s.ops[1],t=s.investigations[0];o.scanStarted=s.world.elapsed;o.scanRemaining=.01;M.setMissionLink(s,1,false);step(s,.1);assert.equal(t.status,'no new observation');assert.notEqual(M.rescueLabView(s).operation.investigations[0].status,t.status);M.setMissionLink(s,1,true);step(s,.5);assert.equal(M.rescueLabView(s).operation.investigations[0].status,'no new observation');assert.equal(M.rescueLabSnapshot(s).survivors.length,0);assert.equal(M.rescueLabSnapshot(s).completedAt,null);});
test('Neural service receives autonomous agents only; accepted histories are delivered rather than fabricated',async()=>{const s=open(2);M.runMission(s,false);M.switchMission(s,'malecns');s.ops[0].authority='operator';M.runMission(s,true);let ids;const loop=new MissionNeuralLoop(async inputs=>{ids=inputs.map(a=>a.id);return inputs.map(a=>response(a.stimulus));});await loop.pump(s,()=>s);assert.deepEqual(ids,[s.world.agents[1].simulation.bug.id]);assert.equal(s.histories[1].samples.length,0);for(let i=0;i<36;i++){M.advanceMission(s,1/60);await loop.pump(s,()=>s);}assert(s.histories[1].samples.length>0);assert.equal(s.histories[0].samples.length,0);loop.dispose();});
test('Pause/resume rejects an old neural request without pausing the fresh mission',async()=>{const s=open();M.runMission(s,false);M.switchMission(s,'malecns');M.runMission(s,true);let release;const loop=new MissionNeuralLoop(inputs=>new Promise(resolve=>release=()=>resolve(inputs.map(a=>response(a.stimulus)))));const pending=loop.pump(s,()=>s);M.runMission(s,false);loop.cancel();M.runMission(s,true);release();await pending;assert(s.world.running);assert.equal(s.world.agents[0].simulation.neural.response,null);assert.equal(s.world.batchFailures,0);loop.dispose();});
test('Physics, battery, commands and observations are identical at 30, 60 and 144 render Hz',()=>{const results=[];for(const hz of [30,60,144]){const s=M.createRescueLab(4);M.runMission(s,true);M.issueCommand(s,0,{kind:'flight'});for(let i=0;i<hz*10;i++)M.advanceMission(s,1/hz);results.push({ticks:s.world.ticks,bugs:s.world.agents.map(a=>a.simulation.bug),ops:s.ops,thermal:s.thermal,view:M.rescueLabSnapshot(s)});}for(const r of results.slice(1))assert.deepEqual(r,results[0]);});
test('Simple, Natural and BioBug embodiment styles cannot change mission trajectories, timing or telemetry',()=>{const results=[];for(const body of ['simple','natural','biobug']){const s=open(2),v=rescueVisuals(()=>({body,motion:'flight'})),visuals=s.world.agents.map(a=>v.createAgent('#58dfba'));M.issueCommand(s,0,{kind:'flight'});for(let i=0;i<300;i++){M.advanceMission(s,1/60);const view=M.rescueLabView(s),frame={agents:view.agents,discoveries:view.rescue.discoveries,selected:0,elapsed:view.elapsed,explored:view.environment.exploration.explored},before=JSON.stringify(s);visuals.forEach((v,i)=>v.update(frame.agents[i].distance,i===0,frame,i));assert.equal(JSON.stringify(s),before);}results.push({bugs:s.world.agents.map(a=>a.simulation.bug),ops:s.ops,report:M.rescueLabSnapshot(s),ticks:s.world.ticks});visuals.forEach(v=>v.group.traverse(o=>{o.geometry?.dispose();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());}));}assert.deepEqual(results[0],results[1]);assert.deepEqual(results[1],results[2]);});
test('A routed second viewpoint records matching heat without changing identity into survivor confirmation',()=>{const s=open(2),source={key:'warm-object',position:{x:165,y:100},surfaceC:36};s.ops.forEach(o=>o.localHeat.sources=[source]);step(s,1);const f=s.thermal.findings[0];assert(f);assert(M.investigateHeat(s,f.id));step(s,35);const task=s.investigations[0];assert.equal(task.status,'observed again');assert(task.finished!==null);assert(s.thermal.findings[0].observers.length===2);assert.equal(M.rescueLabSnapshot(s).survivors.length,0);assert(task.message.includes('unverified'));});
test('Peer collision blocks a manual approach at the same altitude but permits separated flight',()=>{for(const flight of [false,true]){const s=open(2),a=s.world.agents[0].simulation.bug,b=s.world.agents[1].simulation.bug;s.ops[0].authority=s.ops[1].authority='operator';a.position={x:100,y:100};b.position={x:130,y:100};if(flight){s.ops[0].altitude=s.ops[0].targetAltitude=28;s.ops[0].phase='flying';}for(let j=0;j<4;j++){M.issueCommand(s,0,{kind:'manual',forward:1,angular:0});step(s,.5);}if(flight)assert(a.position.x>b.position.x);else assert(a.position.x<b.position.x-a.radius-b.radius);}});
(async()=>{for(const[n,f]of tests){await f();console.log('PASS',n);}console.log(`${tests.length} rescue operation checks passed`);})().catch(e=>{console.error(e);process.exitCode=1;});
