const assert=require('node:assert/strict'),load=require('../scripts/compile_unified_lab.cjs')();
const {ReceivedMotionPlayback,receivedPose}=load('rendering/rescue3d/model'),M=load('unified-lab/rescueMission');
const tests=[],test=(n,f)=>tests.push([n,f]);
const pose=(time,x=time*60,y=0,heading=0)=>({time,x,y,heading,altitude:28,distance:time*60,state:'exploring',motion:'flight'});
function frame(samples,elapsed=2,running=true,connected=true){const last=samples.at(-1);return {agents:[{bug:{id:'a',position:{x:last.x,y:last.y},heading:last.heading,state:last.state,sensors:{},speed:54},color:'#fff',distance:last.distance,altitude:28,motion:'flight',sampleTime:last.time,motionSamples:samples,motionConnected:connected}],selected:0,elapsed,running,explored:[],discoveries:[]};}
test('Received playback interpolates recorded poses and shortest headings without predicting beyond samples',()=>{const a=pose(0,0,0,6.2),b=pose(1,60,0,.1),p=receivedPose([a,b],.5);assert.equal(p.x,30);assert(Math.abs(p.heading-6.291592653589793)<1e-10);assert.deepEqual(receivedPose([a,b],-2),a);assert.deepEqual(receivedPose([a,b],9),b);});
test('Piecewise trajectory playback preserves corners instead of cutting across blocked space',()=>{const s=[pose(0,0,0),pose(.5,0,30),pose(1,30,30)];assert.equal(receivedPose(s,.25).x,0);assert.equal(receivedPose(s,.75).y,30);});
test('Two-Hz radio packets produce continuous render movement, body time and gait distance',()=>{const player=new ReceivedMotionPlayback(),xs=[],times=[];for(let tick=0;tick<300;tick++){const elapsed=tick/60,latest=Math.max(0,Math.floor((elapsed-.3)*2)/2),samples=Array.from({length:Math.round(latest*60)+1},(_,j)=>pose(j/60));const out=player.update(frame(samples,elapsed),1/60).agents[0];xs.push(out.bug.position.x);times.push(out.sampleTime);}for(let j=61;j<xs.length;j++){assert(xs[j]>=xs[j-1]);assert(xs[j]-xs[j-1]<=1.000000001);}assert(xs.filter((v,i)=>i>60&&v!==xs[i-1]).length>200);assert(times.at(-1)<300/60);});
test('Pause and radio loss immediately freeze the displayed pose and animation clock',()=>{const player=new ReceivedMotionPlayback(),f=frame([pose(0),pose(1)],1.5);player.update(f,.1);const stopped=player.update({...f,running:false},.1);for(let i=0;i<10;i++)assert.deepEqual(player.update({...f,elapsed:8,running:false},.1).agents,stopped.agents);for(let i=0;i<10;i++)assert.deepEqual(player.update({...f,elapsed:8,running:true,agents:f.agents.map(a=>({...a,motionConnected:false}))},.1).agents.map(a=>a.bug.position),stopped.agents.map(a=>a.bug.position));});
test('Reset and reconnection discard obsolete playback and never manufacture an unseen gap path',()=>{const player=new ReceivedMotionPlayback();player.update(frame([pose(1),pose(2)],3),.1);const reset=player.update(frame([pose(0,100)],0,false));assert.equal(reset.agents[0].bug.position.x,100);const resumed=player.update(frame([pose(5,400),pose(6,460)],6.5),.1);assert(resumed.agents[0].bug.position.x>=400);assert(resumed.agents[0].bug.position.x<=460);});
test('Display playback leaves raw radio, neural telemetry, observations and complete mission state unchanged',()=>{const s=M.createRescueLab(2),player=new ReceivedMotionPlayback();M.runMission(s,true);for(let i=0;i<120;i++){M.advanceMission(s,1/60);const v=M.rescueLabView(s),f={agents:v.agents,selected:0,elapsed:v.elapsed,running:v.running,discoveries:v.rescue.discoveries,explored:v.environment.exploration.explored},before=JSON.stringify(s),raw=JSON.stringify(f);player.update(f,1/60);assert.equal(JSON.stringify(f),raw);assert.equal(JSON.stringify(s),before);}assert(s.ops.every(o=>o.motionTrace.length<=64));assert(s.ops.every(o=>o.packet.motionSamples.length<=64));});
for(const[n,f]of tests){f();console.log('PASS',n);}console.log(`${tests.length} motion playback checks passed`);
