const assert=require('node:assert/strict'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
const load=require('../scripts/compile_unified_lab.cjs')();
const {createSwarm,advanceSwarm,runSwarm,switchSwarm}=load('simulation/swarm');
const {createThermal,thermalObservation,sampleThermal,thermalView}=load('unified-lab/thermal');
const {thermalMissionView,thermalMissionSnapshot}=load('unified-lab/thermalMission');
const {ThermalFindings}=load('unified-lab/ThermalFindings');
const {systemSummary}=load('simulation/commanderSnapshot');
const tests=[],test=(name,fn)=>tests.push([name,fn]);
function fixture(){const world=createSwarm(1),env=world.agents[0].simulation.environment,bug=world.agents[0].simulation.bug;env.obstacles=[];bug.position={x:100,y:100};bug.heading=0;const thermal=createThermal(env);thermal.sources=[{key:'anonymous',position:{x:140,y:100},surfaceC:32}];return {world,env,bug,thermal,source:thermal.sources[0]};}
test('thermal visibility enforces field of view, range, contrast and opaque walls/debris',()=>{const f=fixture(),observe=()=>thermalObservation(f.env,f.bug,f.source,15,2026);assert(observe());f.bug.heading=Math.PI;assert.equal(observe(),null);f.bug.heading=0;f.source.position.x=220;assert.equal(observe(),null);f.source.position.x=140;f.source.surfaceC=22;assert.equal(observe(),null);f.source.surfaceC=32;for(const kind of ['wall','debris']){f.env.obstacles=[{id:'block',kind,x:120,y:90,width:5,height:20}];assert.equal(observe(),null);}});
test('cold background and warm equipment use the same sensor rules as people',()=>{const f=fixture();const warm={...f.source,classification:'equipment'},person={...f.source,classification:'human'};assert.deepEqual(thermalObservation(f.env,f.bug,warm,15,2026),thermalObservation(f.env,f.bug,person,15,2026));const sources=createThermal(f.world.agents[0].simulation.environment).sources;assert(sources.some(s=>s.key==='warm-equipment'));assert(sources.some(s=>s.key==='warm-rubble'));});
test('injected localization error stays inside reported engineering uncertainty bound',()=>{const f=fixture();let count=0;for(let t=15;t<=1500;t+=15)for(const distance of [5,30,60,85])for(const angle of [-.9,0,.9]){f.source.position={x:100+Math.cos(angle)*distance,y:100+Math.sin(angle)*distance};const o=thermalObservation(f.env,f.bug,f.source,t,2026);if(o){count++;assert(Math.hypot(o.estimatedPosition.x-f.source.position.x,o.estimatedPosition.y-f.source.position.y)<=o.uncertaintyRadius);assert.notStrictEqual(o.estimatedPosition,f.source.position);}}assert(count>500);});
test('repeated heat never confirms identity or survival and loss of view clears current readings',()=>{const f=fixture();for(let t=15;t<=150;t+=15)sampleThermal(f.thermal,f.env,[f.bug],t);assert(f.thermal.findings[0].persistent);assert.equal(f.thermal.events.length,2);const v=thermalMissionView(f.world,f.thermal);assert.equal(v.rescue.confirmed,0);assert.equal(v.rescue.completedAt,null);assert(v.rescue.discoveries.every(d=>d.status==='possible'&&d.confirmedBy.length===0));f.bug.heading=Math.PI;sampleThermal(f.thermal,f.env,[f.bug],165);assert.equal(f.thermal.readings[f.bug.id].signal,0);assert.equal(f.thermal.readings[f.bug.id].apparentC,null);assert.equal(f.thermal.findings[0].latestObservation,2.5);});
test('interrupted sightings reset consecutive-reading persistence',()=>{const f=fixture();sampleThermal(f.thermal,f.env,[f.bug],15);sampleThermal(f.thermal,f.env,[f.bug],30);f.bug.heading=Math.PI;sampleThermal(f.thermal,f.env,[f.bug],45);f.bug.heading=0;sampleThermal(f.thermal,f.env,[f.bug],60);assert.equal(f.thermal.findings[0].persistent,false);sampleThermal(f.thermal,f.env,[f.bug],75);sampleThermal(f.thermal,f.env,[f.bug],90);assert(f.thermal.findings[0].persistent);});
test('public findings hide internal identities, detach positions and retain uncertainty',()=>{const f=fixture();sampleThermal(f.thermal,f.env,[f.bug],15);const v=thermalView(f.thermal,f.bug.id);assert.equal(v.findings[0].id,'T-001');assert(!JSON.stringify(v).includes('anonymous'));v.findings[0].estimatedPosition.x=999;assert.notEqual(f.thermal.findings[0].estimatedPosition.x,999);const html=renderToStaticMarkup(React.createElement(ThermalFindings,{findings:thermalView(f.thermal,f.bug.id).findings,selected:'T-001',onSelect:()=>{},elapsed:2}));assert(html.includes('Identity unknown'));assert(html.includes('uncertainty'));assert(html.includes('1.8'));});
function trial(hz,enabled=true){const world=createSwarm(4),thermal=createThermal(world.agents[0].simulation.environment,world.seed);runSwarm(world,true);for(let i=0;i<30*hz;i++)advanceSwarm(world,1/hz,enabled?()=>sampleThermal(thermal,world.agents[0].simulation.environment,world.agents.map(a=>a.simulation.bug),world.ticks):undefined);return {world,thermal};}
test('thermal observation preserves complete swarm state and runs deterministically across render rates',()=>{const a=trial(60),b=trial(60,false),c=trial(30),d=trial(144);assert.deepEqual(a.world,b.world);for(const other of [c,d])assert.deepEqual(thermalView(a.thermal,'BioBug #1'),thermalView(other.thermal,'BioBug #1'));assert(a.thermal.findings.length>0);const before=JSON.stringify(thermalView(a.thermal,'BioBug #1'));runSwarm(a.world,false);advanceSwarm(a.world,1,()=>sampleThermal(a.thermal,a.world.agents[0].simulation.environment,a.world.agents.map(x=>x.simulation.bug),a.world.ticks));assert.equal(JSON.stringify(thermalView(a.thermal,'BioBug #1')),before);switchSwarm(a.world,'malecns');runSwarm(a.world,true);advanceSwarm(a.world,.1,()=>sampleThermal(a.thermal,a.world.agents[0].simulation.environment,a.world.agents.map(x=>x.simulation.bug),a.world.ticks));assert.equal(JSON.stringify(thermalView(a.thermal,'BioBug #1')),before);assert.equal(createThermal(a.world.agents[0].simulation.environment).findings.length,0);});
test('lab projection and Commander export cannot leak legacy confirmed survivors or hidden sources',()=>{const {world,thermal}=trial(60);assert(world.rescue.discoveries.some(d=>d.status==='confirmed'));const view=thermalMissionView(world,thermal),report=thermalMissionSnapshot(world,thermal);assert.equal(view.rescue.confirmed,0);assert.deepEqual(report.survivors,[]);assert.equal(report.completedAt,null);assert(report.thermalFindings.length>0);for(const e of report.recentEvents)assert(!e.type.includes('SURVIVOR'));const json=JSON.stringify(report);for(const hidden of ['S-01','S-02','warm-equipment','warm-rubble','groundTruthPosition','associations'])assert(!json.includes(hidden),hidden);assert(systemSummary(report).includes('cannot confirm'));});
for(const [name,fn]of tests){fn();console.log('PASS',name);}console.log(`${tests.length} thermal checks passed`);
