const assert=require('node:assert/strict');
const load=require('../scripts/compile_unified_lab.cjs')();
const {createSwarm,runSwarm,advanceSwarm,swarmSnapshot,switchSwarm}=load('simulation/swarm');
const {SwarmNeuralLoop}=load('simulation/swarmNeuralLoop');
const {parseAnatomicalBatch,RescueActivity}=load('unified-lab/activity');
const {rescueVisuals}=load('unified-lab/visuals');
const {CONTROL_MODEL}=load('simulation/neuralClient');
const {acceptNeural}=load('simulation/engine');
const {mapSensors}=load('simulation/sensorMapping');
// Clearly synthetic transport fixtures; real dataset evidence is recorded by compare:rescue-lab.
function response(stimulus,i=0){const l=.1+i*.03,r=.07;return {dataset:'MaleCNS',version:'v1.0',model:CONTROL_MODEL,stimulus,structural_unchanged:true,graph:{neurons:2,edges:1,structural_contacts:3,structural_sha256:'a'.repeat(64)},dna02:{L:{id:'523769',side_field:'somaSide',peak:l},R:{id:'10360',side_field:'somaSide',peak:r}},input_active:1,top_intermediate_types:[],evaluation_seconds:0,activity:{statistic:'peak-over-20-steps-from-rest',body_ids:['523769','10360'],values:[l,r]}};}
const tests=[];const test=(name,fn)=>tests.push([name,fn]);
function frame(s){const v=swarmSnapshot(s);return {...v,discoveries:v.rescue.discoveries,explored:v.environment.exploration.explored};}
function dispose(visuals){const geometry=new Set(),material=new Set();visuals.forEach(v=>v.group.traverse(o=>{if(o.geometry)geometry.add(o.geometry);if(o.material)material.add(o.material);}));geometry.forEach(g=>g.dispose());material.forEach(m=>m.dispose());}
test('Anatomical batches route by agent ID and reject duplicate IDs or invalid per-neuron data atomically',()=>{const inputs=[{id:'a',stimulus:{left:1,front:0,right:0}},{id:'b',stimulus:{left:0,front:0,right:1}}];const raw={results:inputs.map((a,i)=>({id:a.id,response:response(a.stimulus,i)})).reverse()};const parsed=parseAnatomicalBatch(raw,inputs);assert.equal(parsed[0].dna02.L.peak,.1);assert.equal(parsed[1].dna02.L.peak,.13);assert.throws(()=>parseAnatomicalBatch({results:[raw.results[0],raw.results[0]]},inputs));raw.results[0].response.activity.values[0]=999;assert.throws(()=>parseAnatomicalBatch(raw,inputs));});
test('Accepted histories belong to individual agents, are detached, bounded, and cleared across controller changes/reset',()=>{const s=createSwarm(2),activity=new RescueActivity();switchSwarm(s,'malecns');s.agents.forEach((a,i)=>acceptNeural(a.simulation,response(mapSensors(a.simulation.bug.sensors),i),0));activity.observe(s);activity.observe(s);const a=activity.get(s.agents[0].simulation),b=activity.get(s.agents[1].simulation);assert.equal(a.samples.length,1);assert.equal(a.value('523769'),.1);assert.equal(b.value('523769'),.13);s.agents[0].simulation.neural.response.activity.values[0]=.9;assert.equal(a.value('523769'),.1);for(let i=0;i<200;i++){s.agents[0].simulation.elapsed=i;acceptNeural(s.agents[0].simulation,response(mapSensors(s.agents[0].simulation.bug.sensors)),0);activity.observe(s);}assert.equal(a.samples.length,180);switchSwarm(s,'rule-based');activity.observe(s);assert.equal(activity.get(s.agents[0].simulation).samples.length,0);assert.equal(activity.get(createSwarm(1).agents[0].simulation).samples.length,0);});
test('Pausing or resetting during a pending batch never leaks stale samples into an agent inspector',async()=>{for(const reset of [false,true]){const old=createSwarm(2);switchSwarm(old,'malecns');runSwarm(old,true);let current=old,release;const history=new RescueActivity(),loop=new SwarmNeuralLoop(inputs=>new Promise(resolve=>release=()=>resolve(inputs.map((a,i)=>response(a.stimulus,i)))));const pending=loop.pump(old,()=>current,()=>history.observe(current));if(reset)current=createSwarm(2);else runSwarm(old,false);release();await pending;assert.equal(history.get(current.agents[0].simulation).samples.length,0);loop.dispose();}});

test('Held neural proposal stays paired with accepted activity after pause and clears on controller change',()=>{const s=createSwarm(2),h=new RescueActivity();switchSwarm(s,'malecns');runSwarm(s,true);const sim=s.agents[0].simulation;acceptNeural(sim,response(mapSensors(sim.bug.sensors)),0);const proposal=sim.neural.decision.action;h.observe(s);assert.equal(h.proposal(sim),proposal);runSwarm(s,false);assert.equal(sim.neural.decision,null);h.observe(s);assert.equal(h.proposal(sim),proposal);assert.equal(h.proposal(s.agents[1].simulation),'NO_SAMPLE');switchSwarm(s,'rule-based');h.observe(s);assert.equal(h.proposal(sim),'NO_SAMPLE');});
test('Integrated swarm visuals preserve complete 60-second rescue results, hidden targets, and discovery timing',()=>{const a=createSwarm(4),b=createSwarm(4);let look={body:'natural',motion:'flight'};const factory=rescueVisuals(()=>look),visuals=a.agents.map((_,i)=>factory.createAgent(['#58dfba','#f6c970','#82baff','#e9a0ce'][i]));runSwarm(a,true);runSwarm(b,true);for(let tick=0;tick<3600;tick++){advanceSwarm(a,1/60);advanceSwarm(b,1/60);if(tick%12===0){look={body:['natural','biobug','simple'][Math.floor(tick/12)%3],motion:tick%24?'walk':'flight'};a.selected=Math.floor(tick/12)%4;const view=frame(a),before=JSON.stringify(a);assert.equal(view.environment.survivors.length,0);assert.equal(view.environment.hazards.length,0);visuals.forEach((v,i)=>v.update(view.agents[i].distance,i===a.selected,view,i));assert.equal(JSON.stringify(a),before);}}a.selected=b.selected;assert.deepEqual(a,b);assert.equal(a.rescue.completedAt,b.rescue.completedAt);assert(swarmSnapshot(a).rescue.confirmed>0);dispose(visuals);});
test('Flying swarm bodies freeze while paused and restore walking pose without changing their world projection',()=>{const s=createSwarm(8),view=frame(s);let look={body:'biobug',motion:'flight'};const factory=rescueVisuals(()=>look),visuals=view.agents.map(a=>factory.createAgent(a.color));const matrices=v=>{v.group.updateMatrixWorld(true);const arr=[];v.group.traverse(o=>arr.push(o.matrixWorld.toArray()));return arr;};visuals.forEach((v,i)=>{v.update(3,true,view,i);const frozen=matrices(v);v.update(3,true,view,i);assert.deepEqual(matrices(v),frozen);});assert.equal(factory.followHeight(),17);look={body:'natural',motion:'walk'};visuals.forEach((v,i)=>v.update(3,false,view,i));assert.equal(factory.followHeight(),5);dispose(visuals);});
(async()=>{for(const [n,f]of tests){await f();console.log('PASS',n);}console.log(`${tests.length} unified lab checks passed`);})().catch(e=>{console.error(e);process.exitCode=1;});
