const fs=require('node:fs'),assert=require('node:assert/strict');
const load=require('../tests/compile.cjs')();
const {createSwarm,runSwarm,advanceSwarm,swarmSnapshot,switchSwarm}=load('swarm');
const {neuralDue}=load('engine');const {isPositionValid}=load('collision');
const {SwarmNeuralLoop,parseBatch}=load('swarmNeuralLoop');
const duration=Number(process.argv[2]||60);if(!Number.isInteger(duration)||duration<30||duration>300)throw Error('Use 30-300 whole simulated seconds');
const modes=process.argv.includes('--rule-only')?['rule-based']:['rule-based','malecns'];
async function request(inputs,signal){const r=await fetch('http://127.0.0.1:8000/connectome/control-batch',{method:'POST',signal,headers:{'Content-Type':'application/json',Connection:'close'},body:JSON.stringify({agents:inputs})});if(!r.ok)throw Error(`HTTP ${r.status}`);return parseBatch(await r.json(),inputs);}
async function run(mode,count){const s=createSwarm(count,2026,true);switchSwarm(s,mode);runSwarm(s,true);const loop=new SwarmNeuralLoop(request);const started=performance.now();
for(let tick=0;tick<duration*60;tick++){if(mode==='malecns'&&s.agents.some(a=>neuralDue(a.simulation))){await loop.pump(s,()=>s);assert(s.running,'Backend failed');}advanceSwarm(s,1/60);for(const a of s.agents){assert(isPositionValid(a.simulation.environment,a.simulation.bug.position,7));for(const b of s.agents)if(a!==b)assert(Math.hypot(a.simulation.bug.position.x-b.simulation.bug.position.x,a.simulation.bug.position.y-b.simulation.bug.position.y)>=14.249999);}}
loop.dispose();const v=swarmSnapshot(s);assert(Math.abs(s.elapsed-duration)<1e-6);const first=type=>s.rescue.events.find(e=>e.type===type)?.timestamp??null;
return {mode,count,seed:s.seed,duration,firstLifeSignal:first('POSSIBLE LIFE SIGNAL'),firstConfirmedSurvivor:first('SURVIVOR LOCATED'),firstHazard:first('GAS HAZARD DETECTED'),completedAt:s.rescue.completedAt,survivorsConfirmed:v.rescue.confirmed,hazardsDetected:v.rescue.hazards,coverage:v.explored,distance:v.swarmMetrics.distance,contributors:[...new Set(s.rescue.discoveries.flatMap(d=>d.observers))],events:s.rescue.events,localization:s.rescue.discoveries.map(d=>({id:d.id,estimate:d.estimatedPosition,error:Math.hypot(d.estimatedPosition.x-s.rescue.targets.find(t=>t.id===d.id).groundTruthPosition.x,d.estimatedPosition.y-s.rescue.targets.find(t=>t.id===d.id).groundTruthPosition.y)})),batchRequests:s.batchRequests,batchFailures:s.batchFailures,wallSeconds:(performance.now()-started)/1000};}
(async()=>{if(modes.includes('malecns'))await request([{id:'warmup',stimulus:{left:0,front:0,right:0}}],AbortSignal.timeout(15000));const runs=[];for(const mode of modes)for(const count of [1,4]){const a=await run(mode,count),b=await run(mode,count);const stable=({wallSeconds,...rest})=>rest;assert.deepEqual(stable(a),stable(b));runs.push(a);console.log(JSON.stringify({...a,events:undefined,localization:undefined}));}fs.writeFileSync(`docs/RESCUE_EXPERIMENT${modes.length===1?'_RULE_ONLY':''}.json`,JSON.stringify({recordedAt:new Date().toISOString(),note:'One deliberately designed fixed map, demo seed 2026, 60 Hz physics; each configuration repeated exactly excluding wall time. Real backend used for MaleCNS. Simulation units, not physical hardware validation.',repeatedExactly:true,runs},null,2)+'\n');})().catch(e=>{console.error(e);process.exitCode=1;});
