const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const load=require('./compile_unified_lab.cjs')();
const {createSwarm,switchSwarm,runSwarm,advanceSwarm,swarmSnapshot}=load('simulation/swarm');
const {SwarmNeuralLoop,requestBatch}=load('simulation/swarmNeuralLoop');
const {RescueActivity,requestRescueActivity}=load('unified-lab/activity');
const {rescueVisuals}=load('unified-lab/visuals');
const sha=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
async function trial(count,motion){const s=createSwarm(count),activity=new RescueActivity(),paths=[],look={body:motion==='walk'?'natural':'biobug',motion:motion??'walk'},factory=rescueVisuals(()=>look),visuals=motion?s.agents.map((a,i)=>factory.createAgent(swarmSnapshot(s).agents[i].color)):[];
const loop=new SwarmNeuralLoop(motion?requestRescueActivity:requestBatch,()=>0);switchSwarm(s,'malecns');runSwarm(s,true);
try{while(s.ticks<180){await loop.pump(s,()=>s,()=>activity.observe(s));if(!s.running)throw Error(s.agents[0].simulation.neural.error);const before=s.ticks;advanceSwarm(s,1/60);if(s.ticks!==before+1)throw Error('Missing fixed step');paths.push(s.agents.map(a=>({...a.simulation.bug.position,heading:a.simulation.bug.heading})));if(motion){const v=swarmSnapshot(s),frame={...v,explored:v.environment.exploration.explored,discoveries:v.rescue.discoveries},json=JSON.stringify(s);visuals.forEach((visual,i)=>visual.update(v.agents[i].distance,i===s.selected,frame,i));assert.equal(JSON.stringify(s),json);}}
const plain=JSON.parse(JSON.stringify(s));for(const agent of plain.agents){delete agent.simulation.neural.response.activity;delete agent.simulation.neural.response.evaluation_seconds;}
return {state:plain,paths,activity:s.agents.map(a=>({ids:activity.get(a.simulation).ids,samples:activity.get(a.simulation).samples}))};
}finally{loop.dispose();const gs=new Set(),ms=new Set();visuals.forEach(v=>v.group.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)ms.add(o.material);}));gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());}}
(async()=>{const cases=[];for(const count of [1,4,8]){const original=await trial(count,null),walking=await trial(count,'walk'),flying=await trial(count,'flight');for(const run of [walking,flying]){assert.deepEqual(run.paths,original.paths);assert.deepEqual(run.state,original.state);}assert.deepEqual(walking.activity,flying.activity);assert.equal(walking.activity.length,count);assert(walking.activity.every(a=>a.ids.length===295&&a.samples.length===15));cases.push({agents:count,seconds:3,ticks:180,requests_per_run:15,evaluations:count*45,exact_mission_state_and_paths:true,exact_all_neural_activity_across_visuals:true,state_sha256:sha(original.state),trajectory_sha256:sha(original.paths),activity_sha256:sha(walking.activity)});console.log('PASS',count,'agents: original rescue = natural walking lab = cyborg flying lab');}
fs.writeFileSync('docs/UNIFIED_LAB_COMPARISON.json',JSON.stringify({recorded_at:new Date().toISOString(),dataset:'MaleCNS v1.0',scope:'Actual local backend, production swarm scheduler and physics, real Three.js body transforms. HTTP latency fixed to zero for equality; evaluation_seconds excluded. No rendered GPU timing claims.',evaluations:cases.reduce((s,c)=>s+c.evaluations,0),cases},null,2)+'\n');})().catch(e=>{console.error(e);process.exitCode=1;});
