const assert=require('node:assert/strict'),fs=require('node:fs');const load=require('../tests/compile.cjs')();
const {createSwarm,runSwarm,advanceSwarm,switchSwarm,swarmSnapshot}=load('swarm');const {buildMissionSnapshot}=load('commanderSnapshot');const {neuralDue}=load('engine');const {SwarmNeuralLoop,parseBatch}=load('swarmNeuralLoop');
async function neural(agents,signal){const r=await fetch('http://127.0.0.1:8000/connectome/control-batch',{method:'POST',headers:{'Content-Type':'application/json',Connection:'close'},body:JSON.stringify({agents}),signal});assert(r.ok);return parseBatch(await r.json(),agents);}
(async()=>{const status=await (await fetch('http://127.0.0.1:8000/commander/status')).json();const old=JSON.parse(fs.readFileSync('docs/RESCUE_EXPERIMENT.json'));const runs=[],snapshots=[];
await neural([{id:'warmup',stimulus:{left:0,front:0,right:0}}],AbortSignal.timeout(15000));
for(const mode of ['rule-based','malecns']){const s=createSwarm();switchSwarm(s,mode);runSwarm(s,true);const loop=new SwarmNeuralLoop(neural);snapshots.push(buildMissionSnapshot(s));let offlineChecks=0;
for(let i=0;i<3600;i++){if(mode==='malecns'&&s.agents.some(a=>neuralDue(a.simulation)))await loop.pump(s,()=>s);assert(s.running);advanceSwarm(s,1/60);if([479,1799,3599].includes(i))snapshots.push(buildMissionSnapshot(s));if(!status.configured&&[599,2399].includes(i)){const r=await (await fetch('http://127.0.0.1:8000/commander/brief',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({snapshot:buildMissionSnapshot(s),question:'Mission summary'})})).json();assert.equal(r.status,'offline');assert.equal(r.error,'missing_api_key');assert(s.running);offlineChecks++;}}
loop.dispose();const view=swarmSnapshot(s),baseline=old.runs.find(r=>r.mode===mode&&r.count===4);assert.equal(view.explored,baseline.coverage);assert.equal(s.rescue.completedAt,baseline.completedAt);assert.deepEqual(s.rescue.events,baseline.events);runs.push({mode,survivors:view.rescue.confirmed,hazards:view.rescue.hazards,coverage:view.explored,completedAt:s.rescue.completedAt,offlineChecks,unchangedFromMilestone5:true});console.log(runs.at(-1));}
const sizes=snapshots.map(s=>Buffer.byteLength(JSON.stringify(s)));const report={runs,snapshotSizes:sizes,averageSnapshotBytes:sizes.reduce((a,b)=>a+b,0)/sizes.length,liveOpenAIRequests:0,meanAiLatencyMs:null,p95AiLatencyMs:null,note:'No paid requests. Full real MaleCNS backend used. Snapshot samples at 0/8/30/60 seconds for each mode.'};fs.writeFileSync('docs/COMMANDER_VALIDATION.json',JSON.stringify(report,null,2));fs.writeFileSync('docs/COMMANDER_SNAPSHOT_EXAMPLES.json',JSON.stringify(snapshots,null,2));})().catch(e=>{console.error(e);process.exitCode=1;});
