import { lazy, Suspense, useEffect, useState } from 'react';
import App from './App';
import './experiences.css';
const UnifiedLab=lazy(()=>import('./unified-lab/UnifiedLab'));
function selectedExperience(){return location.hash==='#rescue'?'rescue':location.hash==='#virtual-fly'?'experiment':location.hash==='#virtual-lab'?'lab':'home';}
export default function Experiences(){
  const [experience,setExperience]=useState(selectedExperience);
  useEffect(()=>{const change=()=>setExperience(selectedExperience());window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
  if(experience!=='home')return <><div className="experience-return"><a href="#">← CHOOSE EXPERIENCE</a><span>Leaving closes the active run. Re-entry starts fresh.</span></div>{experience==='rescue'?<App/>:<Suspense fallback={<div className="experience-loading">Loading Virtual Fly Lab…</div>}><UnifiedLab key={experience} initial={experience==='experiment'?'experiment':'rescue'}/></Suspense>}</>;
  return <main className="experience-home"><p className="experience-wordmark">✳ BIOBUG</p><p className="experience-kicker">BIOBUG / MISSION & RESEARCH</p><h1>Choose your perspective.</h1><p className="experience-intro">Run a rescue demonstration or enter the unified lab to connect swarm missions with individual neural activity.</p><div className="experience-choices"><section><span className="experience-number">01 / MISSION</span><div className="experience-symbol">⌖</div><h2>BioBug Rescue</h2><p>Search-and-rescue swarm simulation. Explore, share discoveries and brief a human operator.</p><a href="#rescue">ENTER RESCUE <span>↗</span></a><small>Presentation · Technical · 3D Rescue View</small></section><section><span className="experience-number">02 / UNIFIED LAB</span><div className="experience-symbol">⌬</div><h2>Virtual BioBug Lab</h2><p>Detailed fruit flies in a collapsed building. Explore with a swarm, detect life and hazards, and inspect each agent’s neural activity.</p><a href="#virtual-lab">ENTER LAB <span>↗</span></a><small>3D rescue missions · Selected-agent neurons · Controlled fly experiments</small></section></div><p className="experience-footnote">Real structural connectivity. Simulated bodies and neural dynamics. No physical hardware deployment or biological fidelity claim.</p></main>;
}
